///////////////////////////////////////////////////
///////////////////////////////////////////////////
////////// Draw Unfolding Systematic Uncertainty //////////
////////// author: Joonsuk Bae           ////////// 
////////// E-mail: jbae@cern.ch          //////////
////////// Last Modified: 2025           //////////
///////////////////////////////////////////////////
///////////////////////////////////////////////////

#include "Filipad2.h"
#include <TFile.h>
#include <TH1.h>
#include <TH2.h>
#include <TString.h>
#include <TSystem.h>
#include <TMath.h>
#include <TMatrixD.h>
#include <iostream>
#include <vector>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <map>

// ---- Tee stream buffer: duplicates output to both original stream and log file ----
class TeeBuf : public std::streambuf {
public:
  TeeBuf(std::streambuf *orig, std::streambuf *log) : fOrig(orig), fLog(log) {}
protected:
  int overflow(int c) override {
    if (c == EOF) return !EOF;
    int r1 = fOrig->sputc(c);
    int r2 = fLog->sputc(c);
    return (r1 == EOF || r2 == EOF) ? EOF : c;
  }
  int sync() override {
    fOrig->pubsync();
    fLog->pubsync();
    return 0;
  }
private:
  std::streambuf *fOrig, *fLog;
};
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TCanvas.h>
#include <TGraph.h>

#include <RooUnfoldBayes.h>
#include <RooUnfoldResponse.h>
#include <RooUnfoldSvd.h>
#include <TSVDUnfold_local.h>
#include <TParameter.h>
#include <TKey.h>

#include "DrawJetsMCRDependentHelpers.h"

// ============================================================
// Configuration - Hardcoded constants (not using DrawJetsMCFilesTitles.h)
// ============================================================

// File paths
const TString mainDir = "~/cernbox/workspace/O2Physics/jets/AnalysisResults/";
const TString fRoot = "_AnalysisResults.root";

// Data file (reference)
TString refFile = "498133" + fRoot;  // full 2022 pass7
TString refPath = mainDir + refFile;
const char* RefFileDirectories[] = {"jet-spectra-charged"};
const Int_t nRefFileDirectories = 1;

// MC file (for response matrix)
// TString MCfileName = mainDir + "516969" + fRoot;  // LHC25a2b, tuner A (old)
TString MCfileName = mainDir + "596836" + fRoot;  // LHC25a2b, tuner 1p5
// const char* McFileDirectories[] = {"jet-spectra-charged_Nmax1p5"};
const char* McFileDirectories[] = {"jet-spectra-charged"};
const Int_t nMcFileDirectories = 1;

// Binning: detected dynamically from histograms via BuildPtBinning().
// These globals are set once inside LoadUnfoldingInputs() from the actual 2D response matrix.
PtBinning gRecoBin;   // reco axis binning (set from response matrix x-axis)
PtBinning gTruthBin;  // truth axis binning (set from response matrix y-axis)

// Plot ranges (use helpers if available, otherwise local defaults)
const Double_t PlotPtMin = GetPlotPtMin();
const Double_t PlotPtMax = GetPlotPtMax();

// Axis titles
TString JetPtTitleX = "#it{p}_{T, jet}^{part} (GeV/#it{c})";
TString JetPtTitleY = "1/#it{N}_{evt} d#it{N}/d#it{p}_{T}";

// Alternative generator file for prior dependence (POWHEG NLO + Pythia8 Monash, CT18nlo, dijet)
// The ratio POWHEG / (response MC truth) is used to reweight the response matrix
// New R-dependent file: InclusiveJetXSection_R{R*10} (non-UE) and BkgSubtractedJetXSection_R{R*10} (UE-sub)
// Available R values: 0.2, 0.3, 0.4, 0.5, 0.6 (no R=0.1 or R=0.7)
// Raw weighted counts: must normalize by hNEvent
TString kAlternativeGenFile = "~/cernbox/workspace/O2Physics/jets/POWHEG/Pythia8bJetSpectra_dijet_CT18nlo_MonashTune.root";

// MC closure result file (generated by DrawMcClosureTest.C)
TString kMCClosureFile = "plots/MCClosureTest/LHC25a2b_tunerA/MCClosure.root";
TString kMCClosureHistName = "hMCClosureUncertainty";
TString kMCClosureOptimalKName = "optimalSVDk";
TString kMCClosureOptimalBayesIterName = "optimalBayesIter";

// Merge boundary: 20 GeV (must remain bin edge)
const Double_t kMergeBoundary = 20.0;

// Unfolding parameters (will be loaded from MC closure test)
Int_t kNominalSVDk = 8;  // Nominal SVD k parameter (will be loaded from MC closure test)
Int_t kBayesIteration = 1;  // Optimal Bayesian iteration (will be loaded from MC closure test)

// Output
TString kOutputDir = "FinalSystematicUncertainty";
TString kOutputName = "UnfoldingSystematicUncertainty";

// ============================================================
// Helper Functions
// ============================================================

// Plotting helper functions (copied from DrawJetsMCFilesTitles.h)
template <typename T>
void hset(T &hid, TString xtit = "", TString ytit = "", double titoffx = 0.9,
          double titoffy = 1.2, double titsizex = 0.06, double titsizey = 0.06,
          double labeloffx = 0.01, double labeloffy = 0.001,
          double labelsizex = 0.05, double labelsizey = 0.05, int divx = 510,
          int divy = 510) {
  hid.GetXaxis()->CenterTitle(1);
  hid.GetYaxis()->CenterTitle(1);
  hid.GetXaxis()->SetTitleOffset(titoffx);
  hid.GetYaxis()->SetTitleOffset(titoffy);
  hid.GetXaxis()->SetTitleSize(titsizex);
  hid.GetYaxis()->SetTitleSize(titsizey);
  hid.GetXaxis()->SetLabelOffset(labeloffx);
  hid.GetYaxis()->SetLabelOffset(labeloffy);
  hid.GetXaxis()->SetLabelSize(labelsizex);
  hid.GetYaxis()->SetLabelSize(labelsizey);
  hid.GetXaxis()->SetNdivisions(divx);
  hid.GetYaxis()->SetNdivisions(divy);
  hid.GetXaxis()->SetTitle(xtit);
  hid.GetYaxis()->SetTitle(ytit);
}

template <typename T>
void hoptset(T &hid, Double_t N = 1, Color_t color = kBlack, Double_t minX = 0,
             Double_t maxX = 100, Double_t minY = 0, Double_t maxY = 1,
             Double_t MarkerSize = .75, Int_t LineStyle = 1,
             Int_t LineWidth = 1, Int_t MarkerStyle = 20) {
  if (N != 0) {
    if (N == 1) {
      hid.Scale(1. / hid.Integral(), "width");
    } else if (N == 2) {
      hid.Scale(1. / hid.Integral(), "");
    } else {
      hid.Scale(1. / N, "width");
    }
  }
  hid.SetMarkerColor(color);
  hid.SetLineColor(color);
  hid.SetMarkerSize(MarkerSize);
  hid.SetMarkerStyle(MarkerStyle);
  hid.SetLineStyle(LineStyle);
  hid.SetLineWidth(LineWidth);
  hid.GetXaxis()->SetRangeUser(minX, maxX);
  hid.GetYaxis()->SetRangeUser(minY, maxY);
  hid.SetFillColorAlpha(color, 0.3);
}

void optFili(TPad &pid, Int_t gridx, Int_t gridy, Int_t logx, Int_t logy) {
  pid.SetGridy(gridx);
  pid.SetGridx(gridy);
  pid.SetLogx(logx);
  pid.SetLogy(logy);
}

// Find optimal SVD k using d-vector method + bilateral stability criterion.
// Step 1: d-vector finds the signal/noise boundary (standard ALICE method).
// Step 2: Starting from the d-vector boundary, find the first k where BOTH
//         |y(k-1)/y(k)-1| < ε AND |y(k)/y(k+1)-1| < ε (bilateral stability).
//         This ensures k is on the convergence plateau (not at the knee).
Int_t FindOptimalSvdK_Dvector(RooUnfoldResponse *Response, TH1 *hRecoData,
                               TString outputDir, Double_t chi2Threshold = 2.0,
                               Double_t stabilityThreshold = 0.03) {
  const Int_t nBins = hRecoData->GetNbinsX();
  const Int_t maxK = TMath::Min(nBins, 25);
  const Double_t dvecThreshold = 1.0;

  std::cerr << "[Info] SVD k optimization: d-vector (upper bound) + refolding chi2 + bilateral stability" << std::endl;

  // --- Step 1: Unfold at each k, compute refolding chi2 ---
  std::vector<TH1*> results;
  std::vector<double> chi2Values;

  for (Int_t k = 1; k <= maxK; ++k) {
    RooUnfoldSvd unfold(Response, hRecoData, k);
    TH1* h = (TH1*)unfold.Hreco()->Clone(Form("hSVD_stab_k%d", k));
    h->SetDirectory(nullptr);
    results.push_back(h);

    // Refolding chi2: how well does the unfolded result reproduce the measured data?
    TH1* hRefold = (TH1*)Response->ApplyToTruth(h, Form("hRefold_SVD_k%d", k));
    double chi2 = 0.0;
    int ndf = 0;
    if (hRefold) {
      hRefold->SetDirectory(nullptr);
      for (int i = 1; i <= hRecoData->GetNbinsX(); ++i) {
        double ptLow = hRecoData->GetXaxis()->GetBinLowEdge(i);
        double ptHigh = hRecoData->GetXaxis()->GetBinUpEdge(i);
        if (ptLow < PlotPtMin || ptHigh > PlotPtMax) continue;
        const double measured = hRecoData->GetBinContent(i);
        const double measuredErr = hRecoData->GetBinError(i);
        const double refolded = hRefold->GetBinContent(i);
        if (measuredErr > 0 && measured > 0) {
          double pull = (measured - refolded) / measuredErr;
          chi2 += pull * pull;
          ndf++;
        }
      }
      delete hRefold;
    }
    double reducedChi2 = (ndf > 0) ? chi2 / ndf : 1e10;
    chi2Values.push_back(reducedChi2);

    std::cerr << "[Info]   SVD k=" << k
              << ": refolding chi2/ndf = " << reducedChi2 << " (ndf=" << ndf << ")"
              << (reducedChi2 < chi2Threshold ? "  [ok]" : "") << std::endl;
  }

  // --- Step 2: d-vector (upper bound) ---
  // The d-vector identifies the signal/noise boundary: k should not exceed this.
  std::cerr << "[Info] Computing d-vector..." << std::endl;
  RooUnfoldSvd unfoldFull(Response, hRecoData, nBins);
  unfoldFull.Hreco();

  TSVDUnfold_local* svdImpl = unfoldFull.Impl();
  Int_t dvectorK = maxK;
  if (svdImpl) {
    TH1D* hD = svdImpl->GetD();
    if (hD) {
      const Int_t nD = hD->GetNbinsX();
      std::cerr << "[Info] d-vector values:" << std::endl;
      for (Int_t i = 1; i <= nD; ++i) {
        Double_t absDi = TMath::Abs(hD->GetBinContent(i));
        std::cerr << "[Info]   d_" << i << " = " << hD->GetBinContent(i)
                  << "  |d_" << i << "| = " << absDi
                  << (absDi > dvecThreshold ? "  > 1 (signal)" : "  <= 1 (noise)") << std::endl;
      }
      // Robust boundary: require 3+ out of 4 consecutive values below threshold
      // (avoids premature capping from isolated noise pockets, e.g. R=0.2 UE-sub)
      const Int_t windowSize = 4;
      const Int_t noiseRequired = 3;
      for (Int_t i = 1; i <= nD - windowSize + 1; ++i) {
        Int_t noiseCount = 0;
        for (Int_t j = 0; j < windowSize; ++j) {
          if (TMath::Abs(hD->GetBinContent(i + j)) < dvecThreshold)
            noiseCount++;
        }
        if (noiseCount >= noiseRequired) {
          dvectorK = i - 1;
          break;
        }
      }
      if (dvectorK < 1) dvectorK = 1;
    }
  }
  std::cerr << "[Info] d-vector upper bound: k=" << dvectorK << std::endl;

  // --- Step 3: Find first k where chi2/ndf < threshold ---
  // This is the MINIMUM k that adequately describes the data.
  Int_t chi2K = -1;
  for (int i = 0; i < maxK; ++i) {
    if (chi2Values[i] < chi2Threshold) {
      chi2K = i + 1;
      break;
    }
  }

  // Determine scan start: use chi2 convergence as primary, fall back to k=2
  Int_t candidateK;
  if (chi2K > 0) {
    candidateK = chi2K;
    std::cerr << "[Info] Refolding chi2 converged at k=" << chi2K << std::endl;
  } else {
    candidateK = 2;
    std::cerr << "[Warning] Refolding chi2/ndf never dropped below " << chi2Threshold
              << ", starting bilateral stability from k=2." << std::endl;
  }

  // Cap by d-vector: don't search past signal/noise boundary
  Int_t searchMax = TMath::Min(dvectorK + 1, maxK);  // allow +1 beyond boundary for stability check
  std::cerr << "[Info] Bilateral stability scan range: k=" << candidateK
            << " to " << searchMax << " (d-vector cap)" << std::endl;

  // --- Step 4: Bilateral stability within [candidateK, searchMax] ---
  std::cerr << "[Info] Bilateral stability validation (threshold = "
            << stabilityThreshold * 100 << "%):" << std::endl;

  auto maxStepChange = [&](Int_t kA, Int_t kB) -> Double_t {
    Int_t idxA = kA - 1, idxB = kB - 1;
    if (idxA < 0 || idxA >= maxK || idxB < 0 || idxB >= maxK) return 999.;
    Double_t maxRel = 0.0;
    for (Int_t bin = 1; bin <= results[idxA]->GetNbinsX(); ++bin) {
      Double_t ptLow = results[idxA]->GetXaxis()->GetBinLowEdge(bin);
      Double_t ptHigh = results[idxA]->GetXaxis()->GetBinUpEdge(bin);
      if (ptLow < PlotPtMin || ptHigh > PlotPtMax) continue;
      Double_t a = results[idxA]->GetBinContent(bin);
      Double_t b = results[idxB]->GetBinContent(bin);
      if (a > 0 && b > 0) {
        Double_t rel = TMath::Abs(b / a - 1.0);
        if (rel > maxRel) maxRel = rel;
      }
    }
    return maxRel;
  };

  // Scan for bilateral stability plateau: find ALL stable k, pick the one with best chi2.
  // This avoids stopping too early (e.g. R=0.2 UE-sub: stable at k=5 but chi2 keeps improving).
  Int_t firstStableK = -1;
  Int_t bestStableK = -1;
  Double_t bestChi2 = 1e10;
  for (Int_t k = candidateK; k < searchMax; ++k) {
    Double_t backStep = maxStepChange(k - 1, k);
    Double_t fwdStep  = maxStepChange(k, k + 1);
    Bool_t backOK = (backStep < stabilityThreshold);
    Bool_t fwdOK  = (fwdStep  < stabilityThreshold);

    std::cerr << "[Info]   k=" << k
              << ": k-1->k = " << backStep * 100 << "%" << (backOK ? " [ok]" : "")
              << ",  k->k+1 = " << fwdStep * 100 << "%" << (fwdOK ? " [ok]" : "")
              << (backOK && fwdOK ? "  => STABLE" : "") << std::endl;

    if (backOK && fwdOK) {
      if (firstStableK < 0) firstStableK = k;
      // Among all stable k, pick the one with best refolding chi2
      if (k - 1 < (Int_t)chi2Values.size() && chi2Values[k - 1] < bestChi2) {
        bestChi2 = chi2Values[k - 1];
        bestStableK = k;
      }
    }
  }

  Int_t finalK = candidateK;
  Bool_t foundStable = (bestStableK > 0);
  if (foundStable) {
    finalK = bestStableK;
  }

  if (!foundStable) {
    // If no stable point found within d-vector range, use chi2 convergence point
    if (chi2K > 0) {
      finalK = chi2K;
      std::cerr << "[Warning] No bilateral stability within d-vector range. "
                << "Using chi2 convergence k=" << chi2K << std::endl;
    } else {
      std::cerr << "[Warning] SVD optimization: neither chi2 convergence nor bilateral stability found. "
                << "Using k=" << finalK << ". Consider relaxing thresholds." << std::endl;
    }
  } else {
    std::cerr << "[Info] Optimal k=" << finalK
              << " (first stable=" << firstStableK
              << ", best chi2=" << bestChi2
              << " at k=" << bestStableK
              << ", chi2 converged at k=" << chi2K
              << ", d-vector cap at k=" << dvectorK << ")" << std::endl;
  }

  // Cleanup
  for (auto* h : results) delete h;

  if (finalK < 2) finalK = 2;
  if (finalK > 25) finalK = 25;

  std::cerr << "[Info] Optimal SVD k (chi2 + d-vector + stability): " << finalK << std::endl;
  return finalK;
}

// D-vector diagnostic plot: |d_i| vs SVD index with threshold and optimal k
void PlotDvectorDiagnostic(RooUnfoldResponse *Response, TH1 *hRecoData,
                            TString outputDir, Int_t optimalK = -1) {
  const Int_t nBins = hRecoData->GetNbinsX();
  const Double_t noiseExpectation = TMath::Sqrt(2.0 / TMath::Pi());

  RooUnfoldSvd unfoldFull(Response, hRecoData, nBins);
  unfoldFull.Hreco();

  TSVDUnfold_local* svdImpl = unfoldFull.Impl();
  if (!svdImpl) return;
  TH1D* hD = svdImpl->GetD();
  if (!hD) return;

  std::cerr << "[Info] d-vector values (diagnostic):" << std::endl;
  const Int_t nD = hD->GetNbinsX();

  // Build TGraph with integer x-values (hD bin centers may not be integers)
  std::vector<Double_t> xVals(nD), yVals(nD);
  Double_t yMin = 1e30, yMax = 0;
  for (Int_t i = 0; i < nD; ++i) {
    xVals[i] = i + 1;
    yVals[i] = TMath::Abs(hD->GetBinContent(i + 1));
    std::cerr << "[Info]   d_" << (i + 1) << " = " << hD->GetBinContent(i + 1)
              << "  |d_" << (i + 1) << "| = " << yVals[i] << std::endl;
    if (yVals[i] > 0 && yVals[i] < yMin) yMin = yVals[i];
    if (yVals[i] > yMax) yMax = yVals[i];
  }
  if (yMin > 0) yMin *= 0.5;
  else yMin = 0.01;

  TGraph* gD = new TGraph(nD, xVals.data(), yVals.data());
  gD->SetMarkerStyle(20);
  gD->SetMarkerSize(1.0);
  gD->SetMarkerColor(kBlack);
  gD->SetLineColor(kBlack);

  gSystem->mkdir(outputDir, kTRUE);
  TCanvas* cDvec = new TCanvas("cDvec", "SVD d-vector diagnostic", 600, 500);
  cDvec->SetLogy();
  cDvec->SetGridy();

  gD->SetTitle("");
  gD->GetXaxis()->SetTitle("SVD index #it{i}");
  gD->GetYaxis()->SetTitle("|#it{d}_{i}|");
  gD->GetXaxis()->CenterTitle();
  gD->GetYaxis()->CenterTitle();
  gD->GetYaxis()->SetRangeUser(yMin, yMax * 5.0);
  gD->GetXaxis()->SetLimits(0.5, nD + 0.5);
  gD->Draw("AP");

  // Threshold line at |d_i| = 1
  TLine* lineThresh = new TLine(0.5, 1.0, nD + 0.5, 1.0);
  lineThresh->SetLineColor(kOrange + 1);
  lineThresh->SetLineStyle(7);
  lineThresh->SetLineWidth(2);
  lineThresh->Draw("same");

  // Noise expectation line sqrt(2/pi)
  TLine* lineNoise = new TLine(0.5, noiseExpectation, nD + 0.5, noiseExpectation);
  lineNoise->SetLineColor(kRed);
  lineNoise->SetLineStyle(7);
  lineNoise->SetLineWidth(2);
  lineNoise->Draw("same");

  TLegend* leg = new TLegend(0.45, 0.65, 0.88, 0.88);
  leg->SetBorderSize(0);
  leg->SetFillStyle(0);
  leg->SetTextSize(0.035);
  leg->AddEntry(gD, "|d_{i}|", "p");
  leg->AddEntry(lineThresh, "Signal/noise boundary (|d_{i}| = 1)", "l");
  leg->AddEntry(lineNoise, Form("#sqrt{2/#pi} #approx %.2f", noiseExpectation), "l");

  // Vertical line at chosen k (if provided)
  if (optimalK > 0) {
    TLine* lineK = new TLine(optimalK, yMin, optimalK, yMax * 3.0);
    lineK->SetLineColor(kBlue);
    lineK->SetLineStyle(2);
    lineK->SetLineWidth(2);
    lineK->Draw("same");
    leg->AddEntry(lineK, Form("Optimal k = %d", optimalK), "l");
  }

  leg->Draw();

  cDvec->SaveAs(Form("%s/SVD_Dvector_diagnostic.pdf", outputDir.Data()));
  std::cerr << "[Info] d-vector diagnostic plot saved to " << outputDir << "/SVD_Dvector_diagnostic.pdf" << std::endl;
  delete cDvec;
}

// Plot bilateral stability QA: max step-change vs k, using Response + data
// (self-contained: unfolds internally at each k)
void PlotBilateralStability(RooUnfoldResponse *Response, TH1 *hRecoData,
                             Int_t optimalK, Double_t threshold, TString outputDir) {
  const Int_t nBins = hRecoData->GetNbinsX();
  const Int_t maxK = TMath::Min(nBins, 25);
  if (maxK < 3) return;

  // Unfold at each k
  std::vector<TH1*> results;
  for (Int_t k = 1; k <= maxK; ++k) {
    RooUnfoldSvd unfold(Response, hRecoData, k);
    TH1* h = (TH1*)unfold.Hreco()->Clone(Form("hStabPlot_k%d", k));
    h->SetDirectory(nullptr);
    results.push_back(h);
  }

  // Helper: max |y(kA)/y(kB) - 1| across pT bins in [5, 100] GeV
  auto maxStepChange = [&](Int_t kA, Int_t kB) -> Double_t {
    Int_t idxA = kA - 1, idxB = kB - 1;
    if (idxA < 0 || idxA >= maxK || idxB < 0 || idxB >= maxK) return -1.;
    Double_t maxRel = 0.0;
    for (Int_t bin = 1; bin <= results[idxA]->GetNbinsX(); ++bin) {
      Double_t ptLow = results[idxA]->GetXaxis()->GetBinLowEdge(bin);
      Double_t ptHigh = results[idxA]->GetXaxis()->GetBinUpEdge(bin);
      if (ptLow < PlotPtMin || ptHigh > PlotPtMax) continue;
      Double_t a = results[idxA]->GetBinContent(bin);
      Double_t b = results[idxB]->GetBinContent(bin);
      if (a > 0 && b > 0) {
        Double_t rel = TMath::Abs(b / a - 1.0);
        if (rel > maxRel) maxRel = rel;
      }
    }
    return maxRel;
  };

  std::vector<Double_t> kVals, fwdVals, backVals;
  for (Int_t k = 2; k < maxK; ++k) {
    Double_t fwd  = maxStepChange(k, k + 1);
    Double_t back = maxStepChange(k - 1, k);
    if (fwd < 0 || back < 0) continue;
    kVals.push_back(k);
    fwdVals.push_back(fwd * 100.0);
    backVals.push_back(back * 100.0);
  }

  // Cleanup unfolded results
  for (auto* h : results) delete h;

  if (kVals.empty()) return;

  TGraph *gFwd  = new TGraph(kVals.size(), kVals.data(), fwdVals.data());
  TGraph *gBack = new TGraph(kVals.size(), kVals.data(), backVals.data());

  gFwd->SetMarkerStyle(20);  gFwd->SetMarkerSize(1.0);
  gFwd->SetMarkerColor(kRed);  gFwd->SetLineColor(kRed);  gFwd->SetLineWidth(2);
  gBack->SetMarkerStyle(21); gBack->SetMarkerSize(1.0);
  gBack->SetMarkerColor(kBlue); gBack->SetLineColor(kBlue); gBack->SetLineWidth(2);

  TCanvas *c = new TCanvas("cStabDiag", "Bilateral Stability (data)", 700, 500);
  c->SetGridy();

  Double_t yMax = 0;
  for (size_t i = 0; i < fwdVals.size(); ++i)
    yMax = TMath::Max(yMax, TMath::Max(fwdVals[i], backVals[i]));
  yMax = TMath::Max(yMax * 1.3, threshold * 100 * 2.0);

  gBack->SetTitle("");
  gBack->GetXaxis()->SetTitle("SVD regularization parameter #it{k}");
  gBack->GetYaxis()->SetTitle("max |#it{y}(#it{k}#pm1)/#it{y}(#it{k}) #minus 1| (%)");
  gBack->GetXaxis()->CenterTitle();  gBack->GetYaxis()->CenterTitle();
  gBack->GetYaxis()->SetRangeUser(0, yMax);
  gBack->GetXaxis()->SetLimits(kVals.front() - 0.5, kVals.back() + 0.5);
  gBack->Draw("ALP");
  gFwd->Draw("LP same");

  TLine *lineThresh = new TLine(kVals.front() - 0.5, threshold * 100,
                                 kVals.back() + 0.5, threshold * 100);
  lineThresh->SetLineColor(kGreen + 2);
  lineThresh->SetLineStyle(7);  lineThresh->SetLineWidth(2);
  lineThresh->Draw("same");

  TLine *lineK = new TLine(optimalK, 0, optimalK, yMax * 0.9);
  lineK->SetLineColor(kBlack);
  lineK->SetLineStyle(2);  lineK->SetLineWidth(2);
  lineK->Draw("same");

  TLegend *leg = new TLegend(0.45, 0.65, 0.88, 0.88);
  leg->SetBorderSize(0);  leg->SetFillStyle(0);  leg->SetTextSize(0.035);
  leg->AddEntry(gBack, "max |#it{y}(#it{k}#minus1)/#it{y}(#it{k}) #minus 1|", "lp");
  leg->AddEntry(gFwd,  "max |#it{y}(#it{k})/#it{y}(#it{k}+1) #minus 1|", "lp");
  leg->AddEntry(lineThresh, Form("#varepsilon = %.0f%%", threshold * 100), "l");
  leg->AddEntry(lineK, Form("Optimal #it{k} = %d", optimalK), "l");
  leg->Draw();

  gSystem->mkdir(outputDir, kTRUE);
  c->SaveAs(Form("%s/SVD_BilateralStability_diagnostic.pdf", outputDir.Data()));
  std::cerr << "[Info] Bilateral stability plot saved to " << outputDir
            << "/SVD_BilateralStability_diagnostic.pdf" << std::endl;
  delete c;
}

// Bayesian optimization functions now provided by DrawJetsMCRDependentHelpers.h:
//   FindOptimalBayesIter(), PlotBayesChi2Diagnostic(), PlotBayesBilateralStability()

// Kernel-style unfolding helpers
// - Keep fake/miss definitions as: fake = reco - matchedReco, miss = truth - matchedTruth
// - Build unfolding response ONLY from matched pairs (no Fake/Miss filled into RooUnfoldResponse)
struct KernelCorrections {
  TH1* hRecoMatched;   // projX(matched2D)
  TH1* hTruthMatched;  // projY(matched2D)
  TH1* hFake;          // reco - matchedReco
  TH1* hMiss;          // truth - matchedTruth
  TH1* hPurity;        // matchedReco / reco
  TH1* hEfficiency;    // matchedTruth / truth
};

KernelCorrections ComputeKernelCorrections(TH1* hMCReco, TH1* hMCTruth, TH2* h2Matched) {
  KernelCorrections out;
  out.hRecoMatched = nullptr;
  out.hTruthMatched = nullptr;
  out.hFake = nullptr;
  out.hMiss = nullptr;
  out.hPurity = nullptr;
  out.hEfficiency = nullptr;

  if (!hMCReco || !hMCTruth || !h2Matched) {
    std::cerr << "[Error] ComputeKernelCorrections: null input" << std::endl;
    return out;
  }

  out.hRecoMatched = (TH1*)h2Matched->ProjectionX("hRecoMatched_nom", 1, h2Matched->GetNbinsY(), "e");
  out.hTruthMatched = (TH1*)h2Matched->ProjectionY("hTruthMatched_nom", 1, h2Matched->GetNbinsX(), "e");
  if (out.hRecoMatched) out.hRecoMatched->SetDirectory(nullptr);
  if (out.hTruthMatched) out.hTruthMatched->SetDirectory(nullptr);

  // Fake and miss from ORIGINAL counts (must be done before any RM scaling)
  out.hFake = (TH1*)hMCReco->Clone("hFake_nom");
  if (out.hFake) {
    out.hFake->SetDirectory(nullptr);
    out.hFake->Add(out.hRecoMatched, -1.0);
  }
  out.hMiss = (TH1*)hMCTruth->Clone("hMiss_nom");
  if (out.hMiss) {
    out.hMiss->SetDirectory(nullptr);
    out.hMiss->Add(out.hTruthMatched, -1.0);
  }

  // Purity and efficiency (fixed for all unfolding variations)
  out.hPurity = (TH1*)hMCReco->Clone("hPurity_nom");
  if (out.hPurity) {
    out.hPurity->SetDirectory(nullptr);
    out.hPurity->Reset();
    for (Int_t i = 1; i <= out.hPurity->GetNbinsX(); ++i) {
      const double denom = hMCReco->GetBinContent(i);
      const double numer = out.hRecoMatched ? out.hRecoMatched->GetBinContent(i) : 0.0;
      double val = 0.0;
      if (denom > 0) {
        val = numer / denom;
      }
      if (val < 0) val = 0.0;
      if (val > 1) val = 1.0;
      out.hPurity->SetBinContent(i, val);
    }
  }

  out.hEfficiency = (TH1*)hMCTruth->Clone("hEfficiency_nom");
  if (out.hEfficiency) {
    out.hEfficiency->SetDirectory(nullptr);
    out.hEfficiency->Reset();
    for (Int_t i = 1; i <= out.hEfficiency->GetNbinsX(); ++i) {
      const double denom = hMCTruth->GetBinContent(i);
      const double numer = out.hTruthMatched ? out.hTruthMatched->GetBinContent(i) : 0.0;
      double val = 0.0;
      if (denom > 0) {
        val = numer / denom;
      }
      if (val < 0) val = 0.0;
      if (val > 1) val = 1.0;
      out.hEfficiency->SetBinContent(i, val);
    }
  }

  return out;
}

TH1* ApplyPurityCorrection(const TH1* hRecoData, const TH1* hPurity, const char* newName) {
  if (!hRecoData || !hPurity) return nullptr;
  TH1* out = (TH1*)hRecoData->Clone(newName);
  out->SetDirectory(nullptr);
  for (Int_t i = 1; i <= out->GetNbinsX(); ++i) {
    const double x = hRecoData->GetBinContent(i);
    const double ex = hRecoData->GetBinError(i);
    const double p = hPurity->GetBinContent(i);
    out->SetBinContent(i, x * p);
    out->SetBinError(i, ex * p);
  }
  return out;
}

TH1* ApplyEfficiencyCorrection(const TH1* hDetectedTruth, const TH1* hEfficiency, const char* newName) {
  if (!hDetectedTruth || !hEfficiency) return nullptr;
  TH1* out = (TH1*)hDetectedTruth->Clone(newName);
  out->SetDirectory(nullptr);
  for (Int_t i = 1; i <= out->GetNbinsX(); ++i) {
    const double x = hDetectedTruth->GetBinContent(i);
    const double ex = hDetectedTruth->GetBinError(i);
    const double eff = hEfficiency->GetBinContent(i);
    if (eff > 0) {
      out->SetBinContent(i, x / eff);
      out->SetBinError(i, ex / eff);
    } else {
      out->SetBinContent(i, 0.0);
      out->SetBinError(i, 0.0);
    }
  }
  return out;
}

TH2* ReweightMatchedMatrixByTruthWeights(const TH2* h2Matched, const TH1* hTruthWeights, const char* newName) {
  if (!h2Matched || !hTruthWeights) return nullptr;
  TH2* out = (TH2*)h2Matched->Clone(newName);
  out->SetDirectory(nullptr);

  for (Int_t j = 1; j <= out->GetNbinsY(); ++j) {
    const double ptTrue = out->GetYaxis()->GetBinCenter(j);
    const int wbin = hTruthWeights->GetXaxis()->FindBin(ptTrue);
    double w = 1.0;
    if (wbin >= 1 && wbin <= hTruthWeights->GetNbinsX()) {
      w = hTruthWeights->GetBinContent(wbin);
    }
    if (!TMath::Finite(w) || w <= 0.0) {
      w = 1.0;
    }

    for (Int_t i = 1; i <= out->GetNbinsX(); ++i) {
      const double c = out->GetBinContent(i, j);
      const double e = out->GetBinError(i, j);
      out->SetBinContent(i, j, c * w);
      out->SetBinError(i, j, e * w);
    }
  }
  return out;
}

// Load histograms needed for unfolding
struct UnfoldingInputs {
  TH1* hDataReco;      // DJetpt: data reco jet pT
  TH1* hMCReco;        // JetMCDPt: MC reco jet pT
  TH1* hMCTruth;       // JetMCPPt: MC truth jet pT
  TH2* h2Correlate;    // h2HCorrelate: matched 2D histogram
};

UnfoldingInputs LoadUnfoldingInputs(const char* dataFile, const char* mcFile,
                                     const char* dataDir, const char* mcDir,
                                     bool useUEsub = false) {
  UnfoldingInputs inputs;
  inputs.hDataReco = nullptr;
  inputs.hMCReco = nullptr;
  inputs.hMCTruth = nullptr;
  inputs.h2Correlate = nullptr;
  
  // Histogram names depend on UE-sub mode
  const char* hJetPtName = useUEsub ? "h_jet_pt_rhoareasubtracted" : "h_jet_pt";
  const char* hMatchedName = useUEsub
    ? "h2_jet_pt_mcd_jet_pt_mcp_matchedgeo_rhoareasubtracted_mcdetaconstraint"
    : "h2_jet_pt_mcd_jet_pt_mcp_matchedgeo_mcdetaconstraint";

  // Load data reco jet pT
  TFile* dFile = TFile::Open(dataFile, "READ");
  if (!dFile || dFile->IsZombie()) {
    std::cerr << "[Error] Cannot open data file: " << dataFile << std::endl;
    return inputs;
  }

  // Load data reco jet pT (with eta projection if jetEtaCut is set)
  TH1* hDataRecoTemp = LoadJetPtWithEtaCut(dFile, dataDir, useUEsub, "hDataRecoTemp");
  if (!hDataRecoTemp) {
    std::cerr << "[Error] Cannot find jet pT in data file" << std::endl;
    return inputs;
  }

  // Load MC histograms
  TFile* mcFileObj = TFile::Open(mcFile, "READ");
  if (!mcFileObj || mcFileObj->IsZombie()) {
    std::cerr << "[Error] Cannot open MC file: " << mcFile << std::endl;
    return inputs;
  }

  // MC truth: only 1D available (no eta axis) — uses production-level eta cut as-is
  const char* hTruthName = useUEsub ? "h_jet_pt_part_rhoareasubtracted" : "h_jet_pt_part";
  TH1* hMCTruthTemp = (TH1*)mcFileObj->Get(Form("%s/%s", mcDir, hTruthName));
  if (!hMCTruthTemp) {
    std::cerr << "[Error] Cannot find h_jet_pt_part in MC file" << std::endl;
    return inputs;
  }
  hMCTruthTemp->SetDirectory(nullptr);
  if (GetCurrentConfigSet().jetEtaCut >= 0 && GetCurrentConfigSet().productionEtaCut < 0) {
    std::cerr << "[Info] MC truth uses production-level R-dependent eta (no 3D histogram available)."
              << " Response matrix and truth are consistent." << std::endl;
  }

  // MC reco: load with eta projection when jetEtaCut is set
  TH1* hMCRecoTemp = LoadJetPtWithEtaCut(mcFileObj, mcDir, useUEsub, "hMCRecoTemp");
  if (!hMCRecoTemp) {
    std::cerr << "[Error] Cannot find jet pT in MC file" << std::endl;
    return inputs;
  }

  TH2* h2CorrelateTemp = (TH2*)mcFileObj->Get(Form("%s/%s", mcDir, hMatchedName));
  if (!h2CorrelateTemp) {
    std::cerr << "[Error] Cannot find 2D correlate histogram in MC file" << std::endl;
    return inputs;
  }
  h2CorrelateTemp->SetDirectory(nullptr);  // Detach from file before rebinning

  // Detect binning from the response matrix (adapts to whatever range the file has)
  DetectResponseBinning((TH2*)h2CorrelateTemp, gRecoBin, gTruthBin);

  // Rebin 1D histograms using detected binning (safe: handles narrower data range)
  inputs.hDataReco = RebinToTarget(hDataRecoTemp, gRecoBin, "hDataReco");
  inputs.hMCTruth  = RebinToTarget(hMCTruthTemp, gTruthBin, "hMCTruth");
  inputs.hMCReco   = RebinToTarget(hMCRecoTemp, gRecoBin, "hMCReco");

  // Rebin 2D histogram
  TH2F* h2Rebinned = new TH2F("h2CorrelateRebinned", "h2CorrelateRebinned",
                                gRecoBin.nBins, gRecoBin.bins, gTruthBin.nBins, gTruthBin.bins);
  for (Int_t ix = 1; ix <= h2CorrelateTemp->GetNbinsX(); ++ix) {
    for (Int_t iy = 1; iy <= h2CorrelateTemp->GetNbinsY(); ++iy) {
      Double_t content = h2CorrelateTemp->GetBinContent(ix, iy);
      Double_t error = h2CorrelateTemp->GetBinError(ix, iy);
      Int_t xbin = h2Rebinned->GetXaxis()->FindBin(h2CorrelateTemp->GetXaxis()->GetBinCenter(ix));
      Int_t ybin = h2Rebinned->GetYaxis()->FindBin(h2CorrelateTemp->GetYaxis()->GetBinCenter(iy));
      Double_t currentContent = h2Rebinned->GetBinContent(xbin, ybin);
      Double_t currentError = h2Rebinned->GetBinError(xbin, ybin);
      h2Rebinned->SetBinContent(xbin, ybin, currentContent + content);
      h2Rebinned->SetBinError(xbin, ybin, TMath::Sqrt(currentError * currentError + error * error));
    }
  }
  inputs.h2Correlate = h2Rebinned;
  inputs.h2Correlate->SetDirectory(nullptr);
  // delete h2CorrelateTemp;  // Commented out: keep for ROOT browser
  
  // mcFileObj->Close();  // Commented out: keep file open for ROOT browser
  // dFile->Close();  // Commented out: keep file open for ROOT browser
  
  return inputs;
}

// Build RooUnfoldResponse from matched 2D correlation matrix
// - Matched pairs only (no Fake/Miss filled into RooUnfoldResponse)
// - Purity (fake) and efficiency (miss) are handled externally
//
// IMPORTANT: RooUnfold requires Fill() to properly set up internal data structures.
// Directly setting Hresponse() content without Fill() causes unfolding to fail.
//
// For prior dependence: pass a reweighted h2Correlate matrix. The reweighting
// changes the response matrix content and the implicit prior.
RooUnfoldResponse* BuildResponse(TH1* /* hMCReco unused */, TH1* /* hMCTruth unused */,
                                  TH2* h2Correlate, bool /* unused */ = true) {
  if (!h2Correlate) {
    std::cerr << "[Error] BuildResponse: null h2Correlate" << std::endl;
    return nullptr;
  }

  // Get matched projections for response constructor (defines binning)
  TH1* hRecoMatched = h2Correlate->ProjectionX("hRecoMatched_build", 1, h2Correlate->GetNbinsY(), "e");
  TH1* hTruthMatched = h2Correlate->ProjectionY("hTruthMatched_build", 1, h2Correlate->GetNbinsX(), "e");
  hRecoMatched->SetDirectory(nullptr);
  hTruthMatched->SetDirectory(nullptr);

  // Kernel-style: Response is built from MATCHED projections only (no Fake/Miss)
  // 3-arg constructor: directly sets _res=h2Correlate, _mes=hRecoMatched, _tru=hTruthMatched
  // No Fill() loop — avoids doubling _mes/_tru that occurs with 2-arg + Fill pattern
  // Preserves original bin errors (Sumw2) from the 2D matrix
  RooUnfoldResponse* Response = new RooUnfoldResponse(hRecoMatched, hTruthMatched, h2Correlate);

  std::cerr << "[Info] RooUnfoldResponse built with 3-arg constructor (matched pairs, raw counts)" << std::endl;

  // Note: Do not add Miss/Fake here (handled externally via purity/efficiency)

  return Response;
}

// Rebin histogram to new binning
TH1* RebinHistogram(TH1* h, Int_t nBins, const Double_t* binEdges, const char* newName) {
  std::vector<Double_t> binEdgesVec(binEdges, binEdges + nBins + 1);
  TH1* hRebinned = h->Rebin(nBins, newName, binEdgesVec.data());
  if (hRebinned) {
    hRebinned->SetDirectory(nullptr);
  }
  return hRebinned;
}

// Rebin 2D histogram to new binning
// CRITICAL: This function must preserve density (content/(bin width X * bin width Y))
TH2* RebinHistogram2D(TH2* h, Int_t nBinsX, const Double_t* binEdgesX,
                      Int_t nBinsY, const Double_t* binEdgesY, const char* newName) {
  std::vector<Double_t> binEdgesXVec(binEdgesX, binEdgesX + nBinsX + 1);
  std::vector<Double_t> binEdgesYVec(binEdgesY, binEdgesY + nBinsY + 1);
  
  TH2F* hRebinned = new TH2F(newName, newName, nBinsX, binEdgesXVec.data(), nBinsY, binEdgesYVec.data());
  hRebinned->Reset();
  
  // For each bin in original histogram, distribute its content to new bins
  // based on bin overlap (preserving density)
  for (Int_t ix = 1; ix <= h->GetNbinsX(); ++ix) {
    Double_t xLow = h->GetXaxis()->GetBinLowEdge(ix);
    Double_t xHigh = h->GetXaxis()->GetBinUpEdge(ix);
    Double_t xWidth = xHigh - xLow;
    
    for (Int_t iy = 1; iy <= h->GetNbinsY(); ++iy) {
      Double_t yLow = h->GetYaxis()->GetBinLowEdge(iy);
      Double_t yHigh = h->GetYaxis()->GetBinUpEdge(iy);
      Double_t yWidth = yHigh - yLow;
      Double_t content = h->GetBinContent(ix, iy);
      Double_t error = h->GetBinError(ix, iy);
      
      if (content <= 0 || xWidth <= 0 || yWidth <= 0) continue;
      
      // Calculate density (content per unit area)
      Double_t density = content / (xWidth * yWidth);
      Double_t densityErr = error / (xWidth * yWidth);
      
      // Find which new bins overlap with this original bin
      for (Int_t newX = 1; newX <= hRebinned->GetNbinsX(); ++newX) {
        Double_t newXLow = hRebinned->GetXaxis()->GetBinLowEdge(newX);
        Double_t newXHigh = hRebinned->GetXaxis()->GetBinUpEdge(newX);
        Double_t xOverlap = TMath::Max(0.0, TMath::Min(xHigh, newXHigh) - TMath::Max(xLow, newXLow));
        
        if (xOverlap <= 0) continue;
        
        for (Int_t newY = 1; newY <= hRebinned->GetNbinsY(); ++newY) {
          Double_t newYLow = hRebinned->GetYaxis()->GetBinLowEdge(newY);
          Double_t newYHigh = hRebinned->GetYaxis()->GetBinUpEdge(newY);
          Double_t yOverlap = TMath::Max(0.0, TMath::Min(yHigh, newYHigh) - TMath::Max(yLow, newYLow));
          
          if (yOverlap > 0) {
            // Add contribution: density * overlap area
            Double_t overlapArea = xOverlap * yOverlap;
            Double_t contribution = density * overlapArea;
            Double_t contributionErr = densityErr * overlapArea;
            
            Double_t currentContent = hRebinned->GetBinContent(newX, newY);
            Double_t currentError = hRebinned->GetBinError(newX, newY);
            hRebinned->SetBinContent(newX, newY, currentContent + contribution);
            hRebinned->SetBinError(newX, newY, TMath::Sqrt(currentError * currentError + contributionErr * contributionErr));
          }
        }
      }
    }
  }
  hRebinned->SetDirectory(nullptr);
  return hRebinned;
}

// Project alternative unfolded result to nominal binning
// CRITICAL: This function must preserve density (content/bin width)
TH1* ProjectToNominalBinning(TH1* hAlt, const Double_t* nominalBins, Int_t nNominalBins) {
  TH1D* hProjected = new TH1D(Form("%s_projected", hAlt->GetName()), 
                              Form("%s_projected", hAlt->GetTitle()),
                              nNominalBins, nominalBins);
  hProjected->SetDirectory(nullptr);
  hProjected->Reset();
  
  // For each bin in alternative histogram, distribute its content to nominal bins
  // based on bin overlap (preserving density)
  for (Int_t altBin = 1; altBin <= hAlt->GetNbinsX(); ++altBin) {
    Double_t altLow = hAlt->GetXaxis()->GetBinLowEdge(altBin);
    Double_t altHigh = hAlt->GetXaxis()->GetBinUpEdge(altBin);
    Double_t altWidth = altHigh - altLow;
    Double_t altContent = hAlt->GetBinContent(altBin);
    Double_t altError = hAlt->GetBinError(altBin);
    
    if (altContent <= 0 || altWidth <= 0) continue;
    
    // Calculate density (content per unit width)
    Double_t altDensity = altContent / altWidth;
    Double_t altDensityErr = altError / altWidth;
    
    // Find which nominal bins overlap with this alternative bin
    for (Int_t nomBin = 1; nomBin <= hProjected->GetNbinsX(); ++nomBin) {
      Double_t nomLow = hProjected->GetXaxis()->GetBinLowEdge(nomBin);
      Double_t nomHigh = hProjected->GetXaxis()->GetBinUpEdge(nomBin);
      
      // Calculate overlap
      Double_t overlapLow = TMath::Max(altLow, nomLow);
      Double_t overlapHigh = TMath::Min(altHigh, nomHigh);
      Double_t overlapWidth = TMath::Max(0.0, overlapHigh - overlapLow);
      
      if (overlapWidth > 0) {
        // Add contribution: density * overlap width
        Double_t contribution = altDensity * overlapWidth;
        Double_t contributionErr = altDensityErr * overlapWidth;
        
        Double_t currentContent = hProjected->GetBinContent(nomBin);
        Double_t currentError = hProjected->GetBinError(nomBin);
        hProjected->SetBinContent(nomBin, currentContent + contribution);
        hProjected->SetBinError(nomBin, TMath::Sqrt(currentError * currentError + contributionErr * contributionErr));
      }
    }
  }
  
  return hProjected;
}

// Calculate relative uncertainty from ratio
TH1* CalculateRelativeUncertainty(TH1* hNominal, TH1* hVariation) {
  if (!hNominal || !hVariation) return nullptr;
  
  TH1* hRelUnc = (TH1*)hNominal->Clone(Form("relUnc_%s", hVariation->GetName()));
  hRelUnc->SetDirectory(nullptr);
  hRelUnc->Reset();
  
  for (Int_t i = 1; i <= hRelUnc->GetNbinsX(); ++i) {
    Double_t nom = hNominal->GetBinContent(i);
    Double_t var = hVariation->GetBinContent(i);
    
    if (nom > 0) {
      Double_t ratio = var / nom;
      Double_t relUnc = TMath::Abs(ratio - 1.0) * 100.0;  // Convert to percentage
      hRelUnc->SetBinContent(i, relUnc);
    }
  }
  
  return hRelUnc;
}

// Save uncertainty plot with Filipad2 (yield pad + ratio pad)
void SaveUncertaintyPlot(TH1* hNominal, const std::vector<TH1*>& hVariations, 
                         const std::vector<TString>& variationLabels,
                         TH1* hUnc, 
                         const TString& name, const TString& displayName, 
                         const TString& outputDir, Double_t nEvents = 1.0,
                         const TString& nominalLabel = "Nominal") {
  if (!hUnc) {
    std::cerr << "[Warning] Cannot save plot for " << name.Data() << ": uncertainty histogram is null" << std::endl;
    return;
  }
  
  // Create Filipad2 with yield pad (top) and ratio pad (bottom)
  Filipad2* pad = new Filipad2(Form("UnfoldingUnc_%s", name.Data()), 1, 2, 0.4, 100, 50, 0.7, 1, 1);
  pad->Draw();
  TPad* topPad = pad->GetPad(1);
  TPad* bottomPad = pad->GetPad(2);
  optFili(*topPad, 1, 1, 0, 1);  // Linear x, log y
  optFili(*bottomPad, 1, 1, 0, 0);  // Linear x, linear y
  
  topPad->cd();
  topPad->SetTicks(1, 1);
  
  // Store pointers for cleanup after saving
  TH1* hNominalPlot = nullptr;
  std::vector<TH1*> hVarPlots;
  TLegend* legYield = nullptr;
  TH1* hRatioPlot = nullptr;
  TH1* hUncPlot = nullptr;
  TLine* lineZero = nullptr;
  
  // Color palette for variations
  std::vector<Color_t> varColors = {kRed + 1, kBlue + 1, kGreen + 2, kMagenta + 1, kCyan + 1, kOrange + 1, kYellow + 2};
  
  // Draw nominal unfolded result in yield pad
  if (hNominal) {
    hNominalPlot = (TH1*)hNominal->Clone(Form("hNominal_%s", name.Data()));
    hNominalPlot->SetDirectory(nullptr);
    
    hset(*hNominalPlot, JetPtTitleX, JetPtTitleY, 0.9, 1.3, 0.05, 0.05, 0.01, 0.01,
         0.05, 0.05, 510, 505);
    hoptset(*hNominalPlot, nEvents, kBlack, PlotPtMin, PlotPtMax, 1e-8, 1.0, 0.8);
    hNominalPlot->Draw("pe");
    
    // Draw variations if available
    if (!hVariations.empty()) {
      for (size_t i = 0; i < hVariations.size(); ++i) {
        if (!hVariations[i]) continue;
        
        TH1* hVarPlot = (TH1*)hVariations[i]->Clone(Form("hVar_%s_%zu", name.Data(), i));
        hVarPlot->SetDirectory(nullptr);
        hVarPlots.push_back(hVarPlot);
        
        Color_t varColor = (i < varColors.size()) ? varColors[i] : kRed + 1 + (Int_t)i;
        
        hset(*hVarPlot, JetPtTitleX, JetPtTitleY, 0.9, 1.3, 0.05, 0.05, 0.01, 0.01,
             0.05, 0.05, 510, 505);
        hoptset(*hVarPlot, nEvents, varColor, PlotPtMin, PlotPtMax, 1e-8, 1.0, 0.8);
        // Set marker style explicitly for better visibility
        hVarPlot->SetMarkerStyle(20 + (Int_t)i);
        hVarPlot->SetMarkerSize(1.2);
        hVarPlot->Draw("pe same");
      }
      
      // Add legend
      legYield = new TLegend(0.55, 0.70, 0.88, 0.88, NULL, "brNDC");
      legYield->SetTextSize(0.04);
      legYield->SetBorderSize(0);
      legYield->SetFillColorAlpha(0, 0);
      legYield->AddEntry(hNominalPlot, nominalLabel.Data(), "pl");
      for (size_t i = 0; i < hVariations.size() && i < variationLabels.size(); ++i) {
        if (hVariations[i]) {
          legYield->AddEntry(hVarPlots[i], variationLabels[i].Data(), "pl");
        }
      }
      legYield->Draw("same");
    }
  }
  
  // Draw ratio plot in ratio pad (variation/nominal, centered at 1.0)
  bottomPad->cd();
  bottomPad->SetTicks(1, 1);
  
  // Create ratio histograms: variation/nominal OR uncertainty converted to ratio
  std::vector<TH1*> hRatioPlots;
  if (!hVariations.empty() && hNominal) {
    // Case 1: Variations exist (Method, Iteration, Prior, MC closure)
    // For MC closure, hVariations[0] is already the Unfolded/Truth ratio
    // For others, calculate variation/nominal
    for (size_t i = 0; i < hVariations.size(); ++i) {
      if (!hVariations[i]) continue;
      TH1* hRatio = nullptr;
      if (name == "MC_closure") {
        // MC closure: ratio is already Unfolded/Truth, use directly
        hRatio = (TH1*)hVariations[i]->Clone(Form("hRatio_%s_%zu", name.Data(), i));
        hRatio->SetDirectory(nullptr);
      } else {
        // Other sources: calculate variation/nominal
        // Manual ratio: avoid propagating nominal's stat errors into the ratio
        // (TH1::Divide propagates both, inflating errors at high pT for narrow eta)
        hRatio = (TH1*)hVariations[i]->Clone(Form("hRatio_%s_%zu", name.Data(), i));
        hRatio->SetDirectory(nullptr);
        for (Int_t b = 1; b <= hRatio->GetNbinsX(); ++b) {
          Double_t nom = hNominal->GetBinContent(b);
          Double_t var = hRatio->GetBinContent(b);
          if (nom > 0) {
            hRatio->SetBinContent(b, var / nom);
            hRatio->SetBinError(b, 0.0);  // systematic shift only, no stat error
          } else {
            hRatio->SetBinContent(b, 1.0);
            hRatio->SetBinError(b, 0.0);
          }
        }
      }
      hRatioPlots.push_back(hRatio);
    }
    // Use first ratio plot for axis setup (will draw all in loop below)
    if (!hRatioPlots.empty()) {
      hRatioPlot = hRatioPlots[0];
    }
  } else if (hUnc && hNominal) {
    // Case 2: Only uncertainty exists (Jet pT bin, Total) - no variation histogram
    // Convert uncertainty % to ratio: 1.0 ± (uncertainty/100)
    // We'll show upper bound: 1.0 + (uncertainty/100)
    hRatioPlot = (TH1*)hNominal->Clone(Form("hRatio_%s", name.Data()));
    hRatioPlot->SetDirectory(nullptr);
    hRatioPlot->Reset();
    
    for (Int_t i = 1; i <= hRatioPlot->GetNbinsX(); ++i) {
      Double_t unc = hUnc->GetBinContent(i);  // uncertainty in %
      if (unc >= 0) {
        // Convert to ratio: 1.0 + (uncertainty/100)
        // This shows the upper bound of the uncertainty band
        Double_t ratio = 1.0 + (unc / 100.0);
        hRatioPlot->SetBinContent(i, ratio);
        // Error is the uncertainty itself (for visualization)
        hRatioPlot->SetBinError(i, unc / 100.0);
      } else {
        hRatioPlot->SetBinContent(i, 1.0);
        hRatioPlot->SetBinError(i, 0.0);
      }
    }
  } else {
    // Fallback: create empty ratio plot
    hRatioPlot = (TH1*)hNominal->Clone(Form("hRatio_%s", name.Data()));
    hRatioPlot->SetDirectory(nullptr);
    hRatioPlot->Reset();
    for (Int_t i = 1; i <= hRatioPlot->GetNbinsX(); ++i) {
      hRatioPlot->SetBinContent(i, 1.0);
    }
  }
  
  // Set y-axis range around 1.0: default 0.8-1.2, but check if data exceeds
  Double_t ratioMin = 0.8;
  Double_t ratioMax = 1.2;
  // Find actual min/max in all ratio plots
  Double_t dataMin = 1e10;
  Double_t dataMax = -1e10;
  if (!hRatioPlots.empty()) {
    for (size_t i = 0; i < hRatioPlots.size(); ++i) {
      for (Int_t j = 1; j <= hRatioPlots[i]->GetNbinsX(); ++j) {
        Double_t ratio = hRatioPlots[i]->GetBinContent(j);
        if (ratio > 0) {
          dataMin = TMath::Min(dataMin, ratio);
          dataMax = TMath::Max(dataMax, ratio);
        }
      }
    }
  } else if (hRatioPlot) {
    for (Int_t i = 1; i <= hRatioPlot->GetNbinsX(); ++i) {
      Double_t ratio = hRatioPlot->GetBinContent(i);
      if (ratio > 0) {
        dataMin = TMath::Min(dataMin, ratio);
        dataMax = TMath::Max(dataMax, ratio);
      }
    }
  }
  // If data exceeds default range, expand to include it
  if (dataMin < ratioMin) ratioMin = TMath::Max(0.5, dataMin * 0.95);  // Add small margin
  if (dataMax > ratioMax) ratioMax = TMath::Min(2.0, dataMax * 1.05);  // Add small margin
  
  // Draw ratio plots
  if (!hRatioPlots.empty()) {
    // Draw multiple ratio plots (for Iteration dependence with k-1 and k+1)
    bool firstRatio = true;
    for (size_t i = 0; i < hRatioPlots.size(); ++i) {
      Color_t varColor = (i < varColors.size()) ? varColors[i] : kBlue + 1 + i;
      
      hRatioPlots[i]->SetLineWidth(3);
      hRatioPlots[i]->SetLineColor(varColor);
      hRatioPlots[i]->SetMarkerColor(varColor);
      hRatioPlots[i]->SetMarkerStyle(20 + (Int_t)i);  // Explicit cast to Int_t
      hRatioPlots[i]->SetMarkerSize(1.2);
      hRatioPlots[i]->SetFillStyle(0);
      
      // Set axis labels and ranges for ratio pad (only for first)
      if (firstRatio) {
        TString ratioYTitle = (name == "MC_closure") ? "Unfolded / Truth" : "Variation / Nominal";
        hset(*hRatioPlots[i], JetPtTitleX, ratioYTitle, 1.1, 0.9, 0.06, 0.06,
             0.01, 0.01, 0.06, 0.06, 510, 505);
        hRatioPlots[i]->GetXaxis()->SetRangeUser(PlotPtMin, PlotPtMax);
        hRatioPlots[i]->GetYaxis()->SetRangeUser(ratioMin, ratioMax);
        hRatioPlots[i]->Draw("EP");  // Draw points with error bars, no line connection
        firstRatio = false;
      } else {
        hRatioPlots[i]->GetXaxis()->SetRangeUser(PlotPtMin, PlotPtMax);
        hRatioPlots[i]->GetYaxis()->SetRangeUser(ratioMin, ratioMax);
        hRatioPlots[i]->Draw("EP same");  // Draw points with error bars, no line connection
      }
    }
  } else if (hRatioPlot) {
    // Single ratio plot (for Jet pT bin, Total - MC closure uses Case 1 above)
    hRatioPlot->SetLineWidth(3);
    hRatioPlot->SetLineColor(kBlue + 1);
    hRatioPlot->SetMarkerColor(kBlue + 1);
    hRatioPlot->SetMarkerStyle(20);
    hRatioPlot->SetMarkerSize(1.2);
    hRatioPlot->SetFillStyle(0);
    
    // Set axis labels and ranges for ratio pad
    TString ratioYTitle = "Variation / Nominal";
    hset(*hRatioPlot, JetPtTitleX, ratioYTitle, 1.1, 0.9, 0.06, 0.06,
         0.01, 0.01, 0.06, 0.06, 510, 505);
    hRatioPlot->GetXaxis()->SetRangeUser(PlotPtMin, PlotPtMax);
    hRatioPlot->GetYaxis()->SetRangeUser(ratioMin, ratioMax);
    
    hRatioPlot->Draw("EP");  // Draw points with error bars, no line connection
  }
  
  // Draw horizontal line at 1.0
  lineZero = new TLine(PlotPtMin, 1.0, PlotPtMax, 1.0);
  lineZero->SetLineColor(kBlack);
  lineZero->SetLineStyle(2);
  lineZero->SetLineWidth(1);
  lineZero->Draw("same");
  
  // Update canvas before saving
  pad->C->cd();
  pad->C->Update();
  pad->C->Modified();
  
  // Save PDF
  TString pdfFile = Form("%s/%s_%s.pdf", outputDir.Data(), kOutputName.Data(), name.Data());
  pad->C->SaveAs(pdfFile.Data());
  std::cerr << "[Info] Saved PDF: " << pdfFile.Data() << std::endl;
  
  // Cleanup after saving (but don't delete pad - it will be cleaned up by ROOT)
  // Commented out: keep for ROOT browser
  // if (hNominalPlot) delete hNominalPlot;
  // if (hVarPlot) delete hVarPlot;
  // if (legYield) delete legYield;
  // if (hRatioPlot) delete hRatioPlot;
  // if (hUncPlot) delete hUncPlot;
  // if (lineZero) delete lineZero;
  // Note: Don't delete pad - Filipad2 manages its own canvas and deleting it causes segfault
  // The pad will be cleaned up automatically by ROOT
  
  // Save TXT
  TString txtFile = Form("%s/%s_%s.txt", outputDir.Data(), kOutputName.Data(), name.Data());
  std::ofstream txt(txtFile.Data());
  if (!txt.is_open()) {
    std::cerr << "[Warning] Cannot open file for writing: " << txtFile.Data() << std::endl;
    return;
  }
  
  txt << "# Unfolding Systematic Uncertainty: " << displayName.Data() << std::endl;
  txt << "# Format: pT_low pT_high pT_center uncertainty(%)" << std::endl;
  txt << std::fixed << std::setprecision(3);
  
  for (Int_t i = 1; i <= hUnc->GetNbinsX(); ++i) {
    Double_t pTLow = hUnc->GetBinLowEdge(i);
    Double_t pTHigh = hUnc->GetBinLowEdge(i) + hUnc->GetBinWidth(i);
    Double_t pTCenter = hUnc->GetBinCenter(i);
    Double_t unc = hUnc->GetBinContent(i);
    
    // Only save bins within plot range
    if (pTCenter >= PlotPtMin && pTCenter <= PlotPtMax) {
      txt << pTLow << " " << pTHigh << " " << pTCenter << " " << unc << std::endl;
    }
  }
  
  txt.close();
  std::cerr << "[Info] Saved TXT: " << txtFile.Data() << std::endl;
}

// ============================================================
// Main Function
// ============================================================

void DrawUnfoldingSystematicUncertainty(Double_t jetR = 0.4, bool useUEsub = false) {
  // Create output directory first (needed for log file)
  gSystem->MakeDirectory(kOutputDir.Data());

  // Set up log file: tee all cerr and cout to output dir
  TString logPath = Form("%s/log.txt", kOutputDir.Data());
  std::ofstream logFile(logPath.Data());
  TeeBuf teeCerr(std::cerr.rdbuf(), logFile.rdbuf());
  TeeBuf teeCout(std::cout.rdbuf(), logFile.rdbuf());
  std::streambuf *origCerr = std::cerr.rdbuf(&teeCerr);
  std::streambuf *origCout = std::cout.rdbuf(&teeCout);

  std::cerr << "========================================" << std::endl;
  std::cerr << "Drawing Unfolding Systematic Uncertainty" << std::endl;
  std::cerr << "  jetR = " << jetR << ", UE-sub = " << (useUEsub ? "true" : "false") << std::endl;
  std::cerr << "========================================" << std::endl;
  
  // Load MC closure parameters for cross-check validation only
  // Following ALICE convention (cf. Hadi pp5.02, Alfanda pPb5.02, Epple+Mulligan pp5.02):
  //   Nominal k/iter are determined from DATA d-vector, NOT from MC closure.
  //   MC closure validates the unfolding procedure but does not set regularization.
  Int_t closureK = -1, closureIter = -1;
  bool loadedFromClosure = false;
  TFile* closureFile = TFile::Open(kMCClosureFile.Data(), "READ");
  if (closureFile && !closureFile->IsZombie()) {
    TParameter<Int_t>* pOptimalK = (TParameter<Int_t>*)closureFile->Get(kMCClosureOptimalKName.Data());
    TParameter<Int_t>* pOptimalBayesIter = (TParameter<Int_t>*)closureFile->Get(kMCClosureOptimalBayesIterName.Data());

    if (pOptimalK && pOptimalBayesIter) {
      closureK = pOptimalK->GetVal();
      closureIter = pOptimalBayesIter->GetVal();
      loadedFromClosure = true;
      std::cerr << "[Info] MC closure cross-check parameters:" << std::endl;
      std::cerr << "[Info]   SVD k = " << closureK << " (validation only)" << std::endl;
      std::cerr << "[Info]   Bayes iter = " << closureIter << " (validation only)" << std::endl;
    } else {
      std::cerr << "[Warning] MC closure file missing optimal parameters" << std::endl;
    }
  } else {
    std::cerr << "[Warning] Cannot open MC closure file: " << kMCClosureFile.Data() << std::endl;
    std::cerr << "[Warning] Run DrawMcClosureTest first to validate the unfolding procedure." << std::endl;
  }
  
  // Load unfolding inputs
  std::cerr << "[Info] Loading unfolding inputs..." << std::endl;
  UnfoldingInputs inputs = LoadUnfoldingInputs(
    refPath.Data(), MCfileName.Data(),
    RefFileDirectories[0], McFileDirectories[0], useUEsub);
  
  if (!inputs.hDataReco || !inputs.hMCReco || !inputs.hMCTruth || !inputs.h2Correlate) {
    std::cerr << "[Error] Failed to load unfolding inputs" << std::endl;
    return;
  }

  // Kernel-style: compute fake/miss, purity, efficiency from ORIGINAL counts
  KernelCorrections kc = ComputeKernelCorrections(inputs.hMCReco, inputs.hMCTruth, inputs.h2Correlate);
  if (!kc.hPurity || !kc.hEfficiency) {
    std::cerr << "[Error] Failed to compute kernel-style purity/efficiency" << std::endl;
    return;
  }

  // Data input for unfolding: apply purity correction (remove fakes) BEFORE unfolding
  TH1* hDataMatched = ApplyPurityCorrection(inputs.hDataReco, kc.hPurity, "hDataRecoMatched");
  if (!hDataMatched) {
    std::cerr << "[Error] Failed to build purity-corrected data histogram" << std::endl;
    return;
  }

  // Debug: Check data input
  std::cerr << "[Debug] Data input (after purity corr): integral=" << hDataMatched->Integral()
            << ", nBins=" << hDataMatched->GetNbinsX() << std::endl;
  for (Int_t i = 1; i <= TMath::Min(5, hDataMatched->GetNbinsX()); ++i) {
    std::cerr << "[Debug]   Bin " << i << " (pT=" << hDataMatched->GetBinCenter(i)
              << "): " << hDataMatched->GetBinContent(i) << std::endl;
  }

  // Build nominal response matrix
  std::cerr << "[Info] Building nominal response matrix..." << std::endl;
  RooUnfoldResponse* ResponseNominal = BuildResponse(
    inputs.hMCReco, inputs.hMCTruth, inputs.h2Correlate);
  
  // Determine nominal regularization from DATA d-vector + bilateral stability
  // This is the standard ALICE approach: d-vector on data sets k, MC closure only validates
  std::cerr << "[Info] Determining optimal regularization from DATA d-vector + bilateral stability..." << std::endl;
  kNominalSVDk = FindOptimalSvdK_Dvector(ResponseNominal, hDataMatched, kOutputDir);
  kBayesIteration = FindOptimalBayesIter(ResponseNominal, hDataMatched, 20, 2.0, 0.03,
                                         "systematic", kOutputDir.Data());
  std::cerr << "[Info] Data-optimized: SVD k=" << kNominalSVDk << ", Bayes iter=" << kBayesIteration << std::endl;

  // Cross-check with MC closure if available
  if (loadedFromClosure) {
    std::cerr << "[Info] MC closure (validation): SVD k=" << closureK << ", Bayes iter=" << closureIter << std::endl;
    if (kNominalSVDk != closureK || kBayesIteration != closureIter) {
      std::cerr << "[Info] MC closure and data optimization differ (expected: MC has lower statistics)." << std::endl;
      std::cerr << "[Info] Using DATA-optimized values as nominal (standard ALICE practice)." << std::endl;
    }
  }

  // QA plots
  PlotDvectorDiagnostic(ResponseNominal, hDataMatched, kOutputDir, kNominalSVDk);
  PlotBilateralStability(ResponseNominal, hDataMatched, kNominalSVDk, 0.03, kOutputDir);
  // Bayesian QA plots (Chi2, BilateralStability) already generated by FindOptimalBayesIter above

  std::cerr << "[Info] Using parameters: SVD k=" << kNominalSVDk << ", Bayes iter=" << kBayesIteration << std::endl;

  // Warn about potential issues
  if (kBayesIteration < 3) {
    std::cerr << "[WARNING] Bayesian iteration=" << kBayesIteration << " is very low!" << std::endl;
    std::cerr << "[WARNING] iter=1 barely unfolds (close to prior). Method dependence will be large." << std::endl;
    std::cerr << "[WARNING] Check MC closure test or run FindOptimalBayesIter diagnostics." << std::endl;
  }
  if (kNominalSVDk < 4) {
    std::cerr << "[WARNING] SVD k=" << kNominalSVDk << " is very low. Iteration dependence (k+-1) will be large." << std::endl;
  }
  // Note: nTruth=25 bins > nReco=20 bins makes system under-determined
  // The 5 extra truth bins (0-5 GeV) add unconstrained degrees of freedom
  std::cerr << "[Info] Response matrix: nReco=" << gRecoBin.nBins << " bins, nTruth=" << gTruthBin.nBins << " bins" << std::endl;
  if (gTruthBin.nBins > gRecoBin.nBins) {
    std::cerr << "[Info] Note: nTruth > nReco (" << gTruthBin.nBins << " > " << gRecoBin.nBins
              << "). Extra truth bins at low pT are weakly constrained." << std::endl;
  }
  
  // Perform nominal unfolding (method-dependent)
  TH1* hNominalDetected = nullptr;
  if (GetUnfoldMethod() == kUnfoldBayes) {
    std::cerr << "[Info] Performing nominal unfolding (Bayesian iter=" << kBayesIteration << ")..." << std::endl;
    RooUnfoldBayes unfoldNominal(ResponseNominal, hDataMatched, kBayesIteration);
    hNominalDetected = (TH1*)unfoldNominal.Hreco()->Clone("hNominalDetected");
  } else {
    std::cerr << "[Info] Performing nominal unfolding (SVD k=" << kNominalSVDk << ")..." << std::endl;
    RooUnfoldSvd unfoldNominal(ResponseNominal, hDataMatched, kNominalSVDk);
    hNominalDetected = (TH1*)unfoldNominal.Hreco()->Clone("hNominalDetected");
  }
  hNominalDetected->SetDirectory(nullptr);

  // Debug: Check unfolded result before efficiency correction
  std::cerr << "[Debug] Unfolded (before eff corr): integral=" << hNominalDetected->Integral()
            << ", nBins=" << hNominalDetected->GetNbinsX() << std::endl;
  for (Int_t i = 1; i <= TMath::Min(5, hNominalDetected->GetNbinsX()); ++i) {
    std::cerr << "[Debug]   Bin " << i << " (pT=" << hNominalDetected->GetBinCenter(i)
              << "): " << hNominalDetected->GetBinContent(i) << std::endl;
  }

  // Efficiency correction (miss) AFTER unfolding
  TH1* hNominal = ApplyEfficiencyCorrection(hNominalDetected, kc.hEfficiency, "hNominal");
  if (!hNominal) {
    std::cerr << "[Error] Failed to apply efficiency correction to nominal unfolding" << std::endl;
    return;
  }

  // Debug: Check result after efficiency correction
  std::cerr << "[Debug] Unfolded (after eff corr): integral=" << hNominal->Integral()
            << ", nBins=" << hNominal->GetNbinsX() << std::endl;
  for (Int_t i = 1; i <= TMath::Min(5, hNominal->GetNbinsX()); ++i) {
    std::cerr << "[Debug]   Bin " << i << " (pT=" << hNominal->GetBinCenter(i)
              << "): " << hNominal->GetBinContent(i) << std::endl;
  }
  
  // Store systematic uncertainties
  std::vector<TH1*> hUncertainties;
  std::vector<TString> uncertaintyNames;
  // Store variations for plotting (nominal vs variation comparison)
  // Each element is a vector of variations for that source (can be multiple, e.g., k-1 and k+1 for iteration dependence)
  std::vector<std::vector<TH1*>> hVariationsList;
  std::vector<std::vector<TString>> variationLabelsList;
  
  // ============================================================
  // 1. Method Dependence: nominal method vs alternative method
  //    Nominal = GetUnfoldMethod(), alternative = the other
  // ============================================================
  std::cerr << "[Info] Calculating method dependence..." << std::endl;
  std::cerr << "[Info]   Nominal: " << (GetUnfoldMethod() == kUnfoldBayes ? "Bayesian" : "SVD") << std::endl;
  std::cerr << "[Info]   SVD k=" << kNominalSVDk << ", Bayesian iter=" << kBayesIteration << std::endl;

  // hNominal is already the nominal method result; compute variation with alternative method
  TH1* hMethodVarDetected = nullptr;
  TString methodVarLabel;
  if (GetUnfoldMethod() == kUnfoldBayes) {
    // Nominal = Bayesian, variation = SVD
    RooUnfoldSvd unfoldSvdVar(ResponseNominal, hDataMatched, kNominalSVDk);
    hMethodVarDetected = (TH1*)unfoldSvdVar.Hreco()->Clone("hMethodVarDetected");
    methodVarLabel = Form("SVD (k=%d)", kNominalSVDk);
  } else {
    // Nominal = SVD, variation = Bayesian
    RooUnfoldBayes unfoldBayesVar(ResponseNominal, hDataMatched, kBayesIteration);
    hMethodVarDetected = (TH1*)unfoldBayesVar.Hreco()->Clone("hMethodVarDetected");
    methodVarLabel = Form("Bayesian (iter=%d)", kBayesIteration);
  }
  hMethodVarDetected->SetDirectory(nullptr);
  TH1* hMethodVar = ApplyEfficiencyCorrection(hMethodVarDetected, kc.hEfficiency, "hMethodVar");
  if (hMethodVar) {
    hMethodVar->SetDirectory(nullptr);
  }

  // Calculate method dependence uncertainty: nominal vs alternative
  TH1* hMethodUnc = CalculateRelativeUncertainty(hNominal, hMethodVar);
  if (hMethodUnc) {
    hUncertainties.push_back(hMethodUnc);
    uncertaintyNames.push_back("Method_dependence");
    TH1* hMethodVarForPlot = (TH1*)hMethodVar->Clone("hMethodVarForPlot");
    hMethodVarForPlot->SetDirectory(nullptr);
    std::vector<TH1*> methodVariations = {hMethodVarForPlot};
    std::vector<TString> methodLabels = {methodVarLabel};
    hVariationsList.push_back(methodVariations);
    variationLabelsList.push_back(methodLabels);
    // Debug: Print statistics
    {
      Double_t maxUnc = 0.0, meanUnc = 0.0;
      Int_t nBins = 0;
      for (Int_t i = 1; i <= hMethodUnc->GetNbinsX(); ++i) {
        Double_t val = hMethodUnc->GetBinContent(i);
        if (val > 0) {
          maxUnc = TMath::Max(maxUnc, val);
          meanUnc += val;
          nBins++;
        }
      }
      if (nBins > 0) meanUnc /= nBins;
      std::cerr << "[Info] Method dependence calculated: max=" << maxUnc << "%, mean=" << meanUnc << "% (nBins=" << nBins << ")" << std::endl;
    }
  } else {
    hVariationsList.push_back(std::vector<TH1*>());
    variationLabelsList.push_back(std::vector<TString>());
    std::cerr << "[Warning] Method dependence calculation failed!" << std::endl;
  }
  
  // ============================================================
  // 2. Iteration/Regularization Dependence: nominal ± 1
  //    SVD: k ± 1, Bayesian: iter ± 1
  // ============================================================
  std::cerr << "[Info] Calculating iteration dependence..." << std::endl;

  TH1 *hRegMinus1 = nullptr, *hRegPlus1 = nullptr;
  Int_t nomReg, regMinus1, regPlus1;
  TString regLabel;

  if (GetUnfoldMethod() == kUnfoldBayes) {
    nomReg = kBayesIteration;
    regMinus1 = TMath::Max(2, nomReg - 1);
    regPlus1 = TMath::Min(20, nomReg + 1);
    regLabel = "Bayes";
    std::cerr << "[Info] Using data-optimized iter=" << nomReg << ", calculating iter±1 variations" << std::endl;

    RooUnfoldBayes unfoldMinus1(ResponseNominal, hDataMatched, regMinus1);
    TH1* hM1Det = (TH1*)unfoldMinus1.Hreco()->Clone("hRegMinus1Detected");
    hM1Det->SetDirectory(nullptr);
    hRegMinus1 = ApplyEfficiencyCorrection(hM1Det, kc.hEfficiency, "hRegMinus1");
    if (hRegMinus1) hRegMinus1->SetDirectory(nullptr);

    RooUnfoldBayes unfoldPlus1(ResponseNominal, hDataMatched, regPlus1);
    TH1* hP1Det = (TH1*)unfoldPlus1.Hreco()->Clone("hRegPlus1Detected");
    hP1Det->SetDirectory(nullptr);
    hRegPlus1 = ApplyEfficiencyCorrection(hP1Det, kc.hEfficiency, "hRegPlus1");
    if (hRegPlus1) hRegPlus1->SetDirectory(nullptr);
  } else {
    nomReg = kNominalSVDk;
    regMinus1 = TMath::Max(2, nomReg - 1);
    regPlus1 = TMath::Min(20, nomReg + 1);
    regLabel = "SVD";
    std::cerr << "[Info] Using data-optimized k=" << nomReg << ", calculating k±1 variations" << std::endl;

    RooUnfoldSvd unfoldMinus1(ResponseNominal, hDataMatched, regMinus1);
    TH1* hM1Det = (TH1*)unfoldMinus1.Hreco()->Clone("hRegMinus1Detected");
    hM1Det->SetDirectory(nullptr);
    hRegMinus1 = ApplyEfficiencyCorrection(hM1Det, kc.hEfficiency, "hRegMinus1");
    if (hRegMinus1) hRegMinus1->SetDirectory(nullptr);

    RooUnfoldSvd unfoldPlus1(ResponseNominal, hDataMatched, regPlus1);
    TH1* hP1Det = (TH1*)unfoldPlus1.Hreco()->Clone("hRegPlus1Detected");
    hP1Det->SetDirectory(nullptr);
    hRegPlus1 = ApplyEfficiencyCorrection(hP1Det, kc.hEfficiency, "hRegPlus1");
    if (hRegPlus1) hRegPlus1->SetDirectory(nullptr);
  }

  // Calculate max deviation from nominal
  TH1* hIterUnc = (TH1*)hNominal->Clone("hIterUnc");
  hIterUnc->SetDirectory(nullptr);
  hIterUnc->Reset();

  for (Int_t i = 1; i <= hIterUnc->GetNbinsX(); ++i) {
    Double_t nom = hNominal->GetBinContent(i);
    Double_t vMinus1 = hRegMinus1 ? hRegMinus1->GetBinContent(i) : 0.0;
    Double_t vPlus1 = hRegPlus1 ? hRegPlus1->GetBinContent(i) : 0.0;

    if (nom > 0) {
      Double_t devMinus1 = TMath::Abs((vMinus1 / nom) - 1.0) * 100.0;
      Double_t devPlus1 = TMath::Abs((vPlus1 / nom) - 1.0) * 100.0;
      Double_t maxDev = TMath::Max(devMinus1, devPlus1);
      hIterUnc->SetBinContent(i, maxDev);
    }
  }

  hUncertainties.push_back(hIterUnc);
  uncertaintyNames.push_back("Iteration_dependence");
  // Store both variations for plotting
  TH1* hRegMinus1ForPlot = hRegMinus1 ? (TH1*)hRegMinus1->Clone("hRegMinus1ForPlot") : nullptr;
  if (hRegMinus1ForPlot) hRegMinus1ForPlot->SetDirectory(nullptr);
  TH1* hRegPlus1ForPlot = hRegPlus1 ? (TH1*)hRegPlus1->Clone("hRegPlus1ForPlot") : nullptr;
  if (hRegPlus1ForPlot) hRegPlus1ForPlot->SetDirectory(nullptr);
  std::vector<TH1*> iterVariations;
  std::vector<TString> iterLabels;
  if (hRegMinus1ForPlot) {
    iterVariations.push_back(hRegMinus1ForPlot);
    iterLabels.push_back(Form("%s (%s=%d)", regLabel.Data(),
                               GetUnfoldMethod() == kUnfoldBayes ? "iter" : "k", regMinus1));
  }
  if (hRegPlus1ForPlot) {
    iterVariations.push_back(hRegPlus1ForPlot);
    iterLabels.push_back(Form("%s (%s=%d)", regLabel.Data(),
                               GetUnfoldMethod() == kUnfoldBayes ? "iter" : "k", regPlus1));
  }
  hVariationsList.push_back(iterVariations);
  variationLabelsList.push_back(iterLabels);
  // Debug: Print statistics
  {
    Double_t maxUnc = 0.0, meanUnc = 0.0;
    Int_t nBins = 0;
    for (Int_t i = 1; i <= hIterUnc->GetNbinsX(); ++i) {
      Double_t val = hIterUnc->GetBinContent(i);
      if (val > 0) {
        maxUnc = TMath::Max(maxUnc, val);
        meanUnc += val;
        nBins++;
      }
    }
    if (nBins > 0) meanUnc /= nBins;
    std::cerr << "[Info] Iteration dependence calculated: max=" << maxUnc << "%, mean=" << meanUnc << "% (nBins=" << nBins << ")" << std::endl;
  }
  
  // ============================================================
  // 3. Prior Dependence: Alternative generator (POWHEG) vs Response MC
  // ============================================================
  // Method: Reweight response matrix y-axis by POWHEG / (Response MC truth) ratio
  // This tests sensitivity to the assumed truth distribution shape
  std::cerr << "[Info] Calculating prior dependence..." << std::endl;
  std::cerr << "[Info] Method: Reweight response matrix by POWHEG / MC_truth ratio" << std::endl;
  std::cerr << "[Info] MC truth from response matrix used as denominator" << std::endl;

  TH1* hPriorUnc = nullptr;
  const Double_t kPriorRangeMin = 5.0;   // Minimum pT for probability calculation
  const Double_t kPriorRangeMax = 200.0; // Maximum pT for probability calculation

  if (!kAlternativeGenFile.IsNull() && kAlternativeGenFile != "") {
    // Load POWHEG truth (R-dependent: InclusiveJetXSection_R{N} or BkgSubtractedJetXSection_R{N})
    std::cerr << "[Info] Attempting to load POWHEG file: " << kAlternativeGenFile.Data() << std::endl;
    TFile* powhegFile = TFile::Open(kAlternativeGenFile.Data(), "READ");
    if (powhegFile && !powhegFile->IsZombie()) {
      std::cerr << "[Info] POWHEG file opened successfully" << std::endl;

      // Construct R-dependent histogram name
      Int_t iR = (Int_t)(jetR * 10 + 0.5);
      TString powhegHistName = useUEsub
        ? Form("BkgSubtractedJetXSection_R%d", iR)
        : Form("InclusiveJetXSection_R%d", iR);

      TH1* hPOWHEGJetPt = (TH1*)powhegFile->Get(powhegHistName.Data());
      TH1* hPOWHEGNEvent = (TH1*)powhegFile->Get("hNEvent");

      if (!hPOWHEGJetPt) {
        std::cerr << "[Warning] Cannot find " << powhegHistName.Data()
                  << " in POWHEG file (available R: 0.2-0.6)" << std::endl;
      }

      if (hPOWHEGJetPt && hPOWHEGNEvent) {
        std::cerr << "[Info] POWHEG histograms loaded: " << powhegHistName.Data() << std::endl;

        // Denominator: MC truth from response matrix (= PYTHIA JJ MC truth)
        // This is the correct comparison: POWHEG_dijet / PYTHIA_JJ gives NLO vs LO shape difference
        if (!inputs.hMCTruth) {
          std::cerr << "[Error] inputs.hMCTruth is null, skipping prior dependence" << std::endl;
          hVariationsList.push_back(std::vector<TH1*>());
          variationLabelsList.push_back(std::vector<TString>());
        } else {
          std::cerr << "[Info] Using MC truth from response matrix as denominator (PYTHIA JJ)" << std::endl;
          std::cerr << "[Info] MC truth: nBins=" << inputs.hMCTruth->GetNbinsX()
                    << ", integral=" << inputs.hMCTruth->Integral() << std::endl;

          // Normalize POWHEG by number of events
          Double_t nEventsPOWHEG = hPOWHEGNEvent->GetBinContent(1);
          if (nEventsPOWHEG <= 0) nEventsPOWHEG = hPOWHEGNEvent->Integral();

          TH1* hPOWHEGTruth = (TH1*)hPOWHEGJetPt->Clone("hPOWHEGTruth_raw");
          hPOWHEGTruth->SetDirectory(nullptr);

          hPOWHEGTruth->Scale(1.0 / nEventsPOWHEG);
          std::cerr << "[Info] POWHEG: nEvents=" << nEventsPOWHEG
                    << ", integral after norm=" << hPOWHEGTruth->Integral() << std::endl;

          // Rebin POWHEG to match analysis binning (gTruthBin)
          TH1D* hPOWHEGTruthRebinned = new TH1D("hPOWHEGTruth_rebinned", "hPOWHEGTruth_rebinned",
                                               gTruthBin.nBins, gTruthBin.bins);
          hPOWHEGTruthRebinned->SetDirectory(nullptr);
          hPOWHEGTruthRebinned->Reset();

          // Rebin POWHEG using density-preserving method
          for (Int_t i = 1; i <= hPOWHEGTruth->GetNbinsX(); ++i) {
            Double_t origLow = hPOWHEGTruth->GetXaxis()->GetBinLowEdge(i);
            Double_t origHigh = hPOWHEGTruth->GetXaxis()->GetBinUpEdge(i);
            Double_t origWidth = origHigh - origLow;
            Double_t origContent = hPOWHEGTruth->GetBinContent(i);
            Double_t origError = hPOWHEGTruth->GetBinError(i);

            if (origContent <= 0 || origWidth <= 0) continue;
            
            Double_t density = origContent / origWidth;
            Double_t densityErr = origError / origWidth;
            
            for (Int_t j = 1; j <= hPOWHEGTruthRebinned->GetNbinsX(); ++j) {
              Double_t targetLow = hPOWHEGTruthRebinned->GetXaxis()->GetBinLowEdge(j);
              Double_t targetHigh = hPOWHEGTruthRebinned->GetXaxis()->GetBinUpEdge(j);
              
              Double_t overlapLow = TMath::Max(origLow, targetLow);
              Double_t overlapHigh = TMath::Min(origHigh, targetHigh);
              Double_t overlapWidth = TMath::Max(0.0, overlapHigh - overlapLow);
              
              if (overlapWidth > 0) {
                Double_t contribution = density * overlapWidth;
                Double_t contributionErr = densityErr * overlapWidth;
                
                Double_t currentContent = hPOWHEGTruthRebinned->GetBinContent(j);
                Double_t currentError = hPOWHEGTruthRebinned->GetBinError(j);
                hPOWHEGTruthRebinned->SetBinContent(j, currentContent + contribution);
                hPOWHEGTruthRebinned->SetBinError(j, TMath::Sqrt(currentError * currentError + contributionErr * contributionErr));
              }
            }
          }
          
          // Replace POWHEG with rebinned version
          hPOWHEGTruth = hPOWHEGTruthRebinned;

          // Use inputs.hMCTruth as the denominator (already rebinned to ptbinGen)
          TH1* hMCTruthForRatio = (TH1*)inputs.hMCTruth->Clone("hMCTruthForRatio");
          hMCTruthForRatio->SetDirectory(nullptr);

          std::cerr << "[Info] Step 3: Calculating probability distributions (5-200 GeV)..." << std::endl;

          // Calculate probability distributions in 5-200 GeV range
          Int_t binMin = hPOWHEGTruth->GetXaxis()->FindBin(kPriorRangeMin + 1e-6);
          Int_t binMax = hPOWHEGTruth->GetXaxis()->FindBin(kPriorRangeMax - 1e-6);

          Double_t powhegIntegralRange = hPOWHEGTruth->Integral(binMin, binMax);
          Double_t mcTruthIntegralRange = hMCTruthForRatio->Integral(binMin, binMax);

          std::cerr << "[Info] POWHEG integral (5-200 GeV): " << powhegIntegralRange << std::endl;
          std::cerr << "[Info] MC truth integral (5-200 GeV): " << mcTruthIntegralRange << std::endl;

          if (powhegIntegralRange > 0 && mcTruthIntegralRange > 0) {
            // Create probability distributions (normalized to 1.0 in 5-200 GeV range)
            TH1* hPOWHEGProb = (TH1*)hPOWHEGTruth->Clone("hPOWHEGProb");
            hPOWHEGProb->SetDirectory(nullptr);
            hPOWHEGProb->Scale(1.0 / powhegIntegralRange);

            TH1* hMCTruthProb = (TH1*)hMCTruthForRatio->Clone("hMCTruthProb");
            hMCTruthProb->SetDirectory(nullptr);
            hMCTruthProb->Scale(1.0 / mcTruthIntegralRange);

            std::cerr << "[Info] Probability distributions created (normalized in 5-200 GeV range)" << std::endl;
            std::cerr << "[Info]   POWHEG prob integral (5-200 GeV): " << hPOWHEGProb->Integral(binMin, binMax) << std::endl;
            std::cerr << "[Info]   MC truth prob integral (5-200 GeV): " << hMCTruthProb->Integral(binMin, binMax) << std::endl;

            std::cerr << "[Info] Step 4: Calculating ratio = POWHEG_prob / MC_truth_prob..." << std::endl;

            // Per-bin diagnostic: show shape differences
            std::cerr << "[Diagnostic] Per-bin POWHEG vs MC truth probability comparison:" << std::endl;
            for (Int_t ib = binMin; ib <= binMax; ++ib) {
              Double_t ptLow = hPOWHEGProb->GetXaxis()->GetBinLowEdge(ib);
              Double_t ptHigh = hPOWHEGProb->GetXaxis()->GetBinUpEdge(ib);
              Double_t pw = hPOWHEGProb->GetBinContent(ib);
              Double_t mc = hMCTruthProb->GetBinContent(ib);
              Double_t ratio = (mc > 0) ? pw / mc : 0;
              std::cerr << "[Diagnostic]   pT=[" << ptLow << "," << ptHigh << "]: "
                        << "POWHEG=" << pw << ", MCtruth=" << mc
                        << ", ratio=" << ratio << std::endl;
            }

            // Calculate ratio: POWHEG_prob / MC_truth_prob
            TH1* hShapeRatio = (TH1*)hPOWHEGProb->Clone("hShapeRatio");
            hShapeRatio->SetDirectory(nullptr);
            hShapeRatio->Divide(hMCTruthProb);

            // QA Plot: Compare probability distributions
            std::cerr << "[Info] Creating QA plot for probability distributions..." << std::endl;
            Filipad2* qaPad = new Filipad2("PriorDependence_QA_ProbabilityDistributions", 1, 2, 0.4, 100, 50, 0.7, 1, 1);
            qaPad->Draw();
            TPad* qaTopPad = qaPad->GetPad(1);
            TPad* qaBottomPad = qaPad->GetPad(2);
            optFili(*qaTopPad, 1, 1, 0, 1);  // Linear x, log y
            optFili(*qaBottomPad, 1, 1, 0, 0);  // Linear x, linear y

            qaTopPad->cd();
            qaTopPad->SetTicks(1, 1);

            // Clone histograms for plotting
            TH1* hPOWHEGProbPlot = (TH1*)hPOWHEGProb->Clone("hPOWHEGProb_plot");
            hPOWHEGProbPlot->SetDirectory(nullptr);
            TH1* hMCTruthProbPlot = (TH1*)hMCTruthProb->Clone("hMCTruthProb_plot");
            hMCTruthProbPlot->SetDirectory(nullptr);

            // Divide by bin width for proper density representation (non-uniform bins)
            for (Int_t ib = 1; ib <= hPOWHEGProbPlot->GetNbinsX(); ++ib) {
              Double_t w = hPOWHEGProbPlot->GetBinWidth(ib);
              if (w > 0) {
                hPOWHEGProbPlot->SetBinContent(ib, hPOWHEGProbPlot->GetBinContent(ib) / w);
                hPOWHEGProbPlot->SetBinError(ib, hPOWHEGProbPlot->GetBinError(ib) / w);
              }
            }
            for (Int_t ib = 1; ib <= hMCTruthProbPlot->GetNbinsX(); ++ib) {
              Double_t w = hMCTruthProbPlot->GetBinWidth(ib);
              if (w > 0) {
                hMCTruthProbPlot->SetBinContent(ib, hMCTruthProbPlot->GetBinContent(ib) / w);
                hMCTruthProbPlot->SetBinError(ib, hMCTruthProbPlot->GetBinError(ib) / w);
              }
            }

            // Set up histograms for top pad
            hset(*hPOWHEGProbPlot, JetPtTitleX, "d#it{P}/d#it{p}_{T} (GeV/#it{c})^{-1}", 0.9, 1.3, 0.05, 0.05, 0.01, 0.01,
                 0.05, 0.05, 510, 505);
            hoptset(*hPOWHEGProbPlot, 0, kRed + 1, PlotPtMin, PlotPtMax, 1e-5, 1.0, 0.8);
            hPOWHEGProbPlot->SetLineWidth(3);
            hPOWHEGProbPlot->SetMarkerStyle(20);
            hPOWHEGProbPlot->SetMarkerSize(1.2);
            hPOWHEGProbPlot->Draw("pe");

            hset(*hMCTruthProbPlot, JetPtTitleX, "d#it{P}/d#it{p}_{T} (GeV/#it{c})^{-1}", 0.9, 1.3, 0.05, 0.05, 0.01, 0.01,
                 0.05, 0.05, 510, 505);
            hoptset(*hMCTruthProbPlot, 0, kBlue + 1, PlotPtMin, PlotPtMax, 1e-5, 1.0, 0.8);
            hMCTruthProbPlot->SetLineWidth(3);
            hMCTruthProbPlot->SetMarkerStyle(21);
            hMCTruthProbPlot->SetMarkerSize(1.2);
            hMCTruthProbPlot->Draw("pe same");

            // Add legend
            TLegend* qaLeg = new TLegend(0.55, 0.70, 0.88, 0.88, NULL, "brNDC");
            qaLeg->SetTextSize(0.04);
            qaLeg->SetBorderSize(0);
            qaLeg->SetFillColorAlpha(0, 0);
            qaLeg->AddEntry(hPOWHEGProbPlot, "POWHEG", "pl");
            qaLeg->AddEntry(hMCTruthProbPlot, "Response MC truth", "pl");
            qaLeg->Draw("same");

            // Draw ratio plot in bottom pad
            qaBottomPad->cd();
            qaBottomPad->SetTicks(1, 1);

            TH1* hRatioPlot = (TH1*)hShapeRatio->Clone("hRatioPlot_QA");
            hRatioPlot->SetDirectory(nullptr);
            hRatioPlot->SetLineWidth(3);
            hRatioPlot->SetLineColor(kBlack);
            hRatioPlot->SetMarkerColor(kBlack);
            hRatioPlot->SetMarkerStyle(20);
            hRatioPlot->SetMarkerSize(1.2);
            hRatioPlot->SetFillStyle(0);

            hset(*hRatioPlot, JetPtTitleX, "POWHEG / MC truth", 1.1, 0.9, 0.06, 0.06,
                 0.01, 0.01, 0.06, 0.06, 510, 505);
            hRatioPlot->GetXaxis()->SetRangeUser(PlotPtMin, PlotPtMax);
            hRatioPlot->GetYaxis()->SetRangeUser(0.5, 1.5);
            hRatioPlot->Draw("EP");
            
            // Draw horizontal line at 1.0
            TLine* qaLineOne = new TLine(PlotPtMin, 1.0, PlotPtMax, 1.0);
            qaLineOne->SetLineColor(kBlack);
            qaLineOne->SetLineStyle(2);
            qaLineOne->SetLineWidth(1);
            qaLineOne->Draw("same");
            
            // Update canvas and save
            qaPad->C->cd();
            qaPad->C->Update();
            qaPad->C->Modified();
            
            TString qaPdfFile = Form("%s/PriorDependence_QA_ProbabilityDistributions.pdf", kOutputDir.Data());
            qaPad->C->SaveAs(qaPdfFile.Data());
            std::cerr << "[Info] Saved QA plot: " << qaPdfFile.Data() << std::endl;
            
            std::cerr << "[Info] Step 5: Prior reweighting (kernel-style)" << std::endl;
            std::cerr << "[Info]   Keep detector response kernel K(i|j) = P(reco_i | truth_j) fixed" << std::endl;
            std::cerr << "[Info]   Change only truth prior shape via response column reweighting" << std::endl;
            std::cerr << "[Info]   Purity and efficiency corrections remain FIXED (nominal)" << std::endl;

            // Reweight matched response counts by truth-bin weights (POWHEG/PYTHIA ratio).
            // This changes the implicit prior in RooUnfold.
            // IMPORTANT: Purity and efficiency remain FIXED from nominal response.
            TH2* h2CorrelateWeighted = ReweightMatchedMatrixByTruthWeights(inputs.h2Correlate, hShapeRatio, "h2CorrelatePriorWeighted");
            if (!h2CorrelateWeighted) {
              std::cerr << "[Warning] Failed to build prior-weighted matched response matrix" << std::endl;
              hVariationsList.push_back(std::vector<TH1*>());
              variationLabelsList.push_back(std::vector<TString>());
            } else {
              // Use BuildResponse to properly normalize to kernel form (each y-bin column sums to 1)
              // This ensures consistency with the nominal response which is also kernel-normalized
              RooUnfoldResponse* ResponseModified = BuildResponse(nullptr, nullptr, h2CorrelateWeighted, true);
              std::cerr << "[Info] Built prior-weighted response with kernel normalization" << std::endl;

              std::cerr << "[Info] Step 6: Unfolding with prior-weighted response matrix..." << std::endl;
              RooUnfoldSvd unfoldModified(ResponseModified, hDataMatched, kNominalSVDk);
              TH1* hModifiedDetected = (TH1*)unfoldModified.Hreco()->Clone("hModifiedDetected");
              hModifiedDetected->SetDirectory(nullptr);

              // Apply the SAME nominal efficiency correction (fixed)
              TH1* hModified = ApplyEfficiencyCorrection(hModifiedDetected, kc.hEfficiency, "hModifiedUnfolded");
              if (hModified) {
                hModified->SetDirectory(nullptr);
              }

              std::cerr << "[Info] Step 7: Calculating prior dependence uncertainty..." << std::endl;

              // Compare final particle-level spectra (after efficiency correction)
              hPriorUnc = CalculateRelativeUncertainty(hNominal, hModified);
            if (hPriorUnc) {
              hUncertainties.push_back(hPriorUnc);
              uncertaintyNames.push_back("Prior_dependence");
              // Store modified variation for plotting
              TH1* hModifiedForPlot = (TH1*)hModified->Clone("hModifiedUnfoldedForPlot");
              hModifiedForPlot->SetDirectory(nullptr);
              std::vector<TH1*> priorVariations = {hModifiedForPlot};
              std::vector<TString> priorLabels = {"POWHEG shape"};
              hVariationsList.push_back(priorVariations);
              variationLabelsList.push_back(priorLabels);
              // Debug: Print statistics
              {
                Double_t maxUnc = 0.0, meanUnc = 0.0;
                Int_t nBins = 0;
                for (Int_t i = 1; i <= hPriorUnc->GetNbinsX(); ++i) {
                  Double_t val = hPriorUnc->GetBinContent(i);
                  if (val > 0) {
                    maxUnc = TMath::Max(maxUnc, val);
                    meanUnc += val;
                    nBins++;
                  }
                }
                if (nBins > 0) meanUnc /= nBins;
                std::cerr << "[Info] Prior dependence calculated successfully: max=" << maxUnc << "%, mean=" << meanUnc << "% (nBins=" << nBins << ")" << std::endl;
              }
            } else {
              hVariationsList.push_back(std::vector<TH1*>());
              variationLabelsList.push_back(std::vector<TString>());
              std::cerr << "[Warning] Prior dependence calculation failed!" << std::endl;
            }

              // delete ResponseModified;  // Commented out: keep for ROOT browser
              // delete hModifiedDetected;  // Commented out: keep for ROOT browser
              // delete hModified;  // Commented out: keep for ROOT browser
              // delete h2CorrelateWeighted;  // Commented out: keep for ROOT browser
            }
            // delete hShapeRatio;  // Commented out: keep for ROOT browser
            // delete hPOWHEGProb;  // Commented out: keep for ROOT browser
            // delete hMCTruthProb;  // Commented out: keep for ROOT browser
            // delete hPOWHEGTruth;  // Commented out: keep for ROOT browser
            // delete hMCTruthForRatio;  // Commented out: keep for ROOT browser
          } else {
            std::cerr << "[Warning] Cannot calculate probability distributions (zero integrals)" << std::endl;
            hVariationsList.push_back(std::vector<TH1*>());
            variationLabelsList.push_back(std::vector<TString>());
          }
        }  // Close else block from line 1086
      } else {
        std::cerr << "[Warning] Cannot load POWHEG histograms for R=" << jetR << ", skipping prior dependence" << std::endl;
        hVariationsList.push_back(std::vector<TH1*>());
        variationLabelsList.push_back(std::vector<TString>());
      }
    // powhegFile->Close();  // Commented out: keep file open for ROOT browser
    } else {
      std::cerr << "[Error] Cannot open POWHEG file: " << kAlternativeGenFile.Data() << std::endl;
      std::cerr << "[Error] File may not exist or is corrupted. Skipping prior dependence" << std::endl;
      hVariationsList.push_back(std::vector<TH1*>());
      variationLabelsList.push_back(std::vector<TString>());
    }
  } else {
    std::cerr << "[Info] Alternative generator file path not provided, skipping prior dependence (placeholder)" << std::endl;
    hVariationsList.push_back(std::vector<TH1*>());
    variationLabelsList.push_back(std::vector<TString>());
  }
  
  // ============================================================
  // 4. Jet pT Bin Dependence: Varying upper and lower boundaries
  // ============================================================
  // NOTE: According to the paper, this uncertainty is negligible.
  // The paper states: "In Run 2 study, the variations were found to have a negligible impact on the results."
  // Therefore, we set this uncertainty to a very small value (0.1%) as a placeholder.
  // In a proper implementation, one would vary the upper and lower pT boundaries of the unfolding range
  // (e.g., lower boundary: 5 GeV -> 6 GeV, upper boundary: 140 GeV -> 150 GeV) while keeping
  // the same binning scheme, then compare the unfolded results in the common pT range.
  std::cerr << "[Info] Calculating jet pT bin dependence..." << std::endl;
  std::cerr << "[Info] NOTE: According to the paper, this uncertainty is negligible." << std::endl;
  std::cerr << "[Info] Setting to 0.1% as a conservative placeholder." << std::endl;
  
  // Create placeholder uncertainty (negligible, as stated in paper)
  TH1* hBinUnc = (TH1*)hNominal->Clone("hBinUnc");
  hBinUnc->SetDirectory(nullptr);
  hBinUnc->Reset();
  
  // Set to 0.1% (negligible, as per paper)
  for (Int_t i = 1; i <= hBinUnc->GetNbinsX(); ++i) {
    hBinUnc->SetBinContent(i, 0.1);  // 0.1% constant uncertainty
  }
  
  hUncertainties.push_back(hBinUnc);
  uncertaintyNames.push_back("Jet_pT_bin_dependence");
  // No variation for plotting (negligible effect)
  hVariationsList.push_back(std::vector<TH1*>());
  variationLabelsList.push_back(std::vector<TString>());
  
  // Debug: Print statistics
  {
    Double_t maxUnc = 0.0, meanUnc = 0.0;
    Int_t nBins = 0;
    for (Int_t i = 1; i <= hBinUnc->GetNbinsX(); ++i) {
      Double_t val = hBinUnc->GetBinContent(i);
      if (val > 0) {
        maxUnc = TMath::Max(maxUnc, val);
        meanUnc += val;
        nBins++;
      }
    }
    if (nBins > 0) meanUnc /= nBins;
    std::cerr << "[Info] Jet pT bin dependence (negligible, per paper): max=" << maxUnc << "%, mean=" << meanUnc << "% (nBins=" << nBins << ")" << std::endl;
  }
  
  // ============================================================
  // 5. MC Closure (loaded from DrawMcClosureTest_JJMCOnly() output)
  // ============================================================
  std::cerr << "[Info] Loading MC closure uncertainty from file..." << std::endl;
  
  TH1* hMCClosureUnc = nullptr;
  TFile* closureFile2 = TFile::Open(kMCClosureFile.Data(), "READ");
  if (closureFile2 && !closureFile2->IsZombie()) {
    hMCClosureUnc = (TH1*)closureFile2->Get(kMCClosureHistName.Data());
    if (hMCClosureUnc) {
      hMCClosureUnc = (TH1*)hMCClosureUnc->Clone("hMCClosureUnc");
      hMCClosureUnc->SetDirectory(nullptr);
      
      // Rebin to match nominal binning if needed
      if (hMCClosureUnc->GetNbinsX() != hNominal->GetNbinsX()) {
        std::cerr << "[Info] Rebinning MC closure uncertainty to match nominal binning" << std::endl;
        TH1* hRebinned = (TH1*)hNominal->Clone("hMCClosureUnc_rebinned");
        hRebinned->SetDirectory(nullptr);
        hRebinned->Reset();
        
        for (Int_t i = 1; i <= hRebinned->GetNbinsX(); ++i) {
          Double_t binCenter = hRebinned->GetBinCenter(i);
          Int_t srcBin = hMCClosureUnc->GetXaxis()->FindBin(binCenter);
          if (srcBin >= 1 && srcBin <= hMCClosureUnc->GetNbinsX()) {
            hRebinned->SetBinContent(i, hMCClosureUnc->GetBinContent(srcBin));
            hRebinned->SetBinError(i, hMCClosureUnc->GetBinError(srcBin));
          }
        }
        // delete hMCClosureUnc;  // Commented out: keep for ROOT browser
        hMCClosureUnc = hRebinned;
      }
      
      hUncertainties.push_back(hMCClosureUnc);
      uncertaintyNames.push_back("MC_closure");
      // MC closure has no variation (it's already an uncertainty)
      hVariationsList.push_back(std::vector<TH1*>());
      variationLabelsList.push_back(std::vector<TString>());
      // Debug: Print statistics
      {
        Double_t maxUnc = 0.0, meanUnc = 0.0;
        Int_t nBins = 0;
        for (Int_t i = 1; i <= hMCClosureUnc->GetNbinsX(); ++i) {
          Double_t val = hMCClosureUnc->GetBinContent(i);
          if (val > 0) {
            maxUnc = TMath::Max(maxUnc, val);
            meanUnc += val;
            nBins++;
          }
        }
        if (nBins > 0) meanUnc /= nBins;
        std::cerr << "[Info] MC closure uncertainty loaded successfully: max=" << maxUnc << "%, mean=" << meanUnc << "% (nBins=" << nBins << ")" << std::endl;
      }
    } else {
      std::cerr << "[Warning] Cannot find MC closure histogram, using placeholder" << std::endl;
      // Create placeholder constant uncertainty
      hMCClosureUnc = (TH1*)hNominal->Clone("hMCClosureUnc");
      hMCClosureUnc->SetDirectory(nullptr);
      hMCClosureUnc->Reset();
      for (Int_t i = 1; i <= hMCClosureUnc->GetNbinsX(); ++i) {
        hMCClosureUnc->SetBinContent(i, 4.0);  // Placeholder: 4% constant
      }
      hUncertainties.push_back(hMCClosureUnc);
      uncertaintyNames.push_back("MC_closure");
      hVariationsList.push_back(std::vector<TH1*>());
      variationLabelsList.push_back(std::vector<TString>());
    }
    // closureFile2->Close();  // Commented out: keep file open for ROOT browser
  } else {
    std::cerr << "[Warning] MC closure file not found: " << kMCClosureFile.Data() << std::endl;
    std::cerr << "[Warning] Using placeholder (constant 4%). Please run DrawMcClosureTest_JJMCOnly() first!" << std::endl;
    // Create placeholder constant uncertainty
    hMCClosureUnc = (TH1*)hNominal->Clone("hMCClosureUnc");
    hMCClosureUnc->SetDirectory(nullptr);
    hMCClosureUnc->Reset();
    for (Int_t i = 1; i <= hMCClosureUnc->GetNbinsX(); ++i) {
      hMCClosureUnc->SetBinContent(i, 4.0);  // Placeholder: 4% constant
    }
    hUncertainties.push_back(hMCClosureUnc);
    uncertaintyNames.push_back("MC_closure");
    hVariationsList.push_back(std::vector<TH1*>());
    variationLabelsList.push_back(std::vector<TString>());
  }
  
  // ============================================================
  // Calculate total unfolding uncertainty (quadrature sum)
  // ============================================================
  std::cerr << "[Info] Calculating total unfolding uncertainty..." << std::endl;
  
  TH1* hTotalUnc = (TH1*)hUncertainties[0]->Clone("hTotalUnfoldingUncertainty");
  hTotalUnc->SetDirectory(nullptr);
  hTotalUnc->Reset();
  
  for (Int_t i = 1; i <= hTotalUnc->GetNbinsX(); ++i) {
    Double_t sumOfSquares = 0.0;
    for (size_t j = 0; j < hUncertainties.size(); ++j) {
      Double_t value = hUncertainties[j]->GetBinContent(i);
      sumOfSquares += value * value;
    }
    Double_t total = TMath::Sqrt(sumOfSquares);
    hTotalUnc->SetBinContent(i, total);
  }
  
  // ============================================================
  // Save to ROOT file
  // ============================================================
  TString outputFile = Form("%s/%s.root", kOutputDir.Data(), kOutputName.Data());
  TFile* outFile = TFile::Open(outputFile.Data(), "RECREATE");
  
  // Save all uncertainties
  for (size_t i = 0; i < hUncertainties.size(); ++i) {
    hUncertainties[i]->Write(uncertaintyNames[i].Data());
  }
  hTotalUnc->Write("Total_unfolding_uncertainty");
  
  // Also save nominal unfolded result for reference
  hNominal->Write("hNominalUnfolded");
  
  // outFile->Close();  // Commented out: keep file open for ROOT browser
  
  std::cerr << "[Info] Unfolding systematic uncertainties saved to: " << outputFile.Data() << std::endl;
  
  // ============================================================
  // Save individual source plots and text files
  // ============================================================
  std::cerr << "[Info] Saving individual source plots and text files..." << std::endl;
  
  // Map uncertainty names to display names
  std::map<TString, TString> displayNames;
  displayNames["Method_dependence"] = "Method Dependence";
  displayNames["Iteration_dependence"] = "Iteration Dependence";
  displayNames["Prior_dependence"] = "Prior Dependence";
  displayNames["Jet_pT_bin_dependence"] = "Jet p_{T} Bin Dependence";
  displayNames["MC_closure"] = "MC Closure";
  
  // Map uncertainty names to nominal labels (for legend)
  std::map<TString, TString> nominalLabels;
  nominalLabels["Method_dependence"] = Form("SVD (k=%d)", kNominalSVDk);
  nominalLabels["Iteration_dependence"] = Form("SVD (k=%d)", kNominalSVDk);
  nominalLabels["Prior_dependence"] = "Response MC prior";
  nominalLabels["Jet_pT_bin_dependence"] = "Nominal binning";
  nominalLabels["MC_closure"] = "Nominal";
  nominalLabels["Total_unfolding_uncertainty"] = "Nominal";
  
  // Get event count for normalization (from DATA file, not MC)
  // This is used to show per-event yield in the SaveUncertaintyPlot yield pad
  Double_t nEvents = 1.0;
  TFile* dataFileForEvents = TFile::Open(refPath.Data(), "READ");
  if (dataFileForEvents && !dataFileForEvents->IsZombie()) {
    TDirectory* dataDir = dynamic_cast<TDirectory*>(dataFileForEvents->Get(RefFileDirectories[0]));
    if (dataDir) {
      TH1* hCollisions = (TH1*)dataDir->Get("h_collisions");
      if (hCollisions) {
        nEvents = hCollisions->GetBinContent(hCollisions->FindBin(3.5));  // occupancycut = all cuts passed
        if (nEvents <= 0) {
          nEvents = hCollisions->Integral();
        }
        std::cerr << "[Info] Data events (occupancycut = all cuts) for normalization: " << nEvents << std::endl;
      }
    }
  }
  if (nEvents <= 0) {
    nEvents = 1.0;  // Fallback
    std::cerr << "[Warning] Could not load data event count, using nEvents=1" << std::endl;
  }
  
  // Save each source
  std::cerr << "[Info] Total number of uncertainty sources: " << hUncertainties.size() << std::endl;
  for (size_t i = 0; i < hUncertainties.size(); ++i) {
    TString name = uncertaintyNames[i];
    TString displayName = displayNames.count(name) ? displayNames[name] : name;
    TString nominalLabel = nominalLabels.count(name) ? nominalLabels[name] : "Nominal";
    std::vector<TH1*> hVars = (i < hVariationsList.size()) ? hVariationsList[i] : std::vector<TH1*>();
    std::vector<TString> varLabels = (i < variationLabelsList.size()) ? variationLabelsList[i] : std::vector<TString>();
    std::cerr << "[Info] Saving plot " << (i+1) << "/" << hUncertainties.size() << ": " << name.Data() << std::endl;
    SaveUncertaintyPlot(hNominal, hVars, varLabels, hUncertainties[i], name, displayName, kOutputDir, nEvents, nominalLabel);
    std::cerr << "[Info] Completed plot " << (i+1) << "/" << hUncertainties.size() << std::endl;
  }
  
  // Save total uncertainty (no variation, just uncertainty)
  TString totalNominalLabel = nominalLabels.count("Total_unfolding_uncertainty") ? nominalLabels["Total_unfolding_uncertainty"] : "Nominal";
  SaveUncertaintyPlot(hNominal, std::vector<TH1*>(), std::vector<TString>(), hTotalUnc, "Total_unfolding_uncertainty", "Total Unfolding Uncertainty", kOutputDir, nEvents, totalNominalLabel);
  
  std::cerr << "[Info] All individual source plots and text files saved" << std::endl;
  std::cerr << "========================================" << std::endl;
  
  // Cleanup - Commented out: keep all objects for ROOT browser
  // delete ResponseNominal;
  // // Note: hSVDOpt was removed (we use hNominal directly for method dependence)
  // delete hBayesOpt;
  // delete hKMinus1;
  // delete hKPlus1;
  // // Note: Jet pT bin dependence variations removed (negligible, per paper)
  // delete inputs.hDataReco;
  // delete inputs.hMCReco;
  // delete inputs.hMCTruth;
  // delete inputs.h2Correlate;
  // for (auto h : hUncertainties) delete h;
  // // Cleanup variations (all cloned variations need to be deleted)
  // for (size_t i = 0; i < hVariationsList.size(); ++i) {
  //   for (size_t j = 0; j < hVariationsList[i].size(); ++j) {
  //     TH1* h = hVariationsList[i][j];
  //     if (h) {
  //       delete h;  // All variations in hVariationsList are clones, safe to delete
  //     }
  //   }
  // }
  // delete hTotalUnc;
  // delete hNominal;

  // Restore original streams
  std::cerr.rdbuf(origCerr);
  std::cout.rdbuf(origCout);
  logFile.close();
  std::cerr << "[Info] Log saved to " << logPath.Data() << std::endl;
}
